### ISSUE TITLE
Haptic Feedback

### ISSUE THREAD

**Issue by jtmuller5** [flutter-tizen/plugins#115]
It would be cool if we could tap into the available vibration motors on Tizen devices (e.g. to vibrate when an timer ends). There is a new package that supports haptic feedback on Android and iOS called [flutter_haptic](https://pub.dev/packages/flutter_haptic) that might be useful.

Again, thanks for the awesome plugins. I've got a few apps working now for my Galaxy watch thanks to you guys.

**Comment by swift-kim** [comment]
Flutter has built-in support for haptic feedbacks (short vibration events): https://api.flutter.dev/flutter/services/HapticFeedback-class.html

This feature has been implemented on Tizen as well (https://github.com/flutter-tizen/engine/pull/75), although it's not available in the latest published engine build yet. If you want to try out the feature earlier, please follow the instructions in https://github.com/flutter-tizen/flutter-tizen/wiki/Miscellaneous#getting-the-latest-engine-build to get the latest unstable engine from our CI server. Also you may need to add the `http://tizen.org/privilege/feedback` privilege to the `tizen-manifest.xml` file to use the feature.

Thank you!

**Comment by swift-kim** [comment]
The new engine binary was [released](https://github.com/flutter-tizen/engine/releases/tag/cd524ba), and you can update to it by pulling the latest tool commit (run `git pull` in the flutter-tizen directory).

By the way it looks like the required privilege is `http://tizen.org/privilege/haptic` but not `http://tizen.org/privilege/feedback`. @pwasowski2 We need to update this error message at some time.

```sh
E/ConsoleMessage( 3898): platform_channel.cc: Play(129) > feedback_play_type() failed with error: [-13] (Permission denied)
E/ConsoleMessage( 3898): platform_channel.cc: HandleMethodCall(244) > No permission to run HapticFeedback.lightImpact(). Add "http://tizen.org/privilege/feedback" privilege to tizen-manifest.xml to use this method: Could not vibrate
E/ConsoleMessage( 3898): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: PlatformException(No permission to run HapticFeedback.lightImpact(). Add "http://tizen.org/privilege/feedback" privilege to tizen-manifest.xml to use this method, Could not vibrate, null, null)
```

**Comment by pwasowski2** [comment]
@swift-kim, I have prepared a fix for this: https://github.com/flutter-tizen/engine/pull/109

**Comment by swift-kim** [comment]
I'll close this issue. Please leave a comment if you need any further information.
