### ISSUE TITLE
Migrate to "plus" plugins

### ISSUE THREAD

**Issue by swift-kim** [flutter-tizen/plugins#116]
Flutter community plus plugins: https://plus.fluttercommunity.dev

Google is officially deprecating their first-party plugins in favor of these plus packages.

https://medium.com/flutter/whats-new-in-flutter-2-2-fd00c65e2039#ca45

> You should migrate your code to the “plus” packages soon and, in the coming weeks, the corresponding packages from Google will be updated to recommend that you do so.

https://github.com/flutter/plugins/pull/3971

**Comment by HakkyuKim** [comment]
- [ ] battery_plus
- [ ] connectivity_plus
- [ ] device_info_plus
- [ ] package_info_plus
- [ ] sensors_plus
- [ ] share_plus
- [ ] network_info_plus (corresponds to wifi_info_flutter)

**Comment by bbrto21** [comment]
I'm working on sensors_plus

**Comment by bbrto21** [comment]
All migrations are complete.
