### ISSUE TITLE
Resolve the limitation of FFI-based plugins

### ISSUE THREAD

**Issue by swift-kim** [flutter-tizen/plugins#123]
FFI-based plugins (path_provider_tizen, shared_preferences_tizen, url_launcher_tizen) currently only work when running in the main isolate and require additional initialization to run in secondary isolates: https://github.com/flutter-tizen/plugins/pull/122#pullrequestreview-674847105

**Comment by bbrto21** [comment]
to solve this limitation, do we need re-implement plugins based on native?

**Comment by swift-kim** [comment]
No, we need to check how other platforms tackle this problem but I had not enough time to investigate.

**Comment by swift-kim** [comment]
- I tested `path_provider_windows` on Windows and it worked without problem on secondary isolates. I'm still not exactly sure how the Dart plugin registry for Windows is different from flutter-tizen's.
- `generated_main.dart` was not generated by flutter_tools even with https://github.com/flutter/flutter/pull/79669 applied on Windows. I don't know why.
- Still https://github.com/flutter/flutter/pull/79669 will land to the stable branch soon and it would be better to re-implement flutter-tizen's Dart plugin registry based on the official one. In fact its approach is not quite different from ours, but the main difference is that `generateMainDartWithPluginRegistrant` (equivalent of `_createEntrypoint` for Tizen) is part of the build graph.
- Consider adding `implements:` attributes to Tizen plugins' pubspecs. It's not quite necessary tho because the attribute doesn't do very much thing.

**Comment by swift-kim** [comment]
I'll test https://github.com/swift-kim/flutter-tizen/commit/1ed4ee777119563adfd8f512f975309c086a247c when the next stable Flutter version is released.

Related engine PR: https://github.com/flutter/engine/pull/25496

**Comment by swift-kim** [comment]
The implementation of the third solution in https://github.com/flutter-tizen/flutter-tizen/pull/177#issuecomment-887479619 can be found at: https://github.com/swift-kim/flutter-tizen/commit/6fd8233b3cf90aca62aac7b163403d18d7526a3f

The commit should land after the next Flutter stable release.

cc @HakkyuKim

**Comment by HakkyuKim** [comment]
@swift-kim That was really fast! Thank you!
I'll have a closer look tomorrow.

**Comment by swift-kim** [comment]
I tried invoking `InvokeDartPluginRegistrantIfAvailable` (`Dart_RootLibrary`~`Dart_Invoke`) after initializing secondary isolates but encountered only some segmentation faults. I'm not sure where I can safely put the code (I tried in `DartIsolateInitializeCallback` and `SpawnIsolateTask:Run`).

**Comment by swift-kim** [comment]
My conclusion is that plugins are generally not expected to work properly inside isolates. This applies to other platforms as well, regardless of the underlying implementation mechanism (platform channel or Dart plugin registrant). (There's even a third-party package called [flutter_isolate](https://pub.dev/packages/flutter_isolate) that allows invoking plugins from isolates.)

The only workaround is to call the `register` function of a plugin (Dart plugin) before invoking its API from an isolate.

Example (path_provider_tizen):

```dart
import 'package:flutter/foundation.dart';
import 'package:path_provider/path_provider.dart';
import 'package:path_provider_tizen/path_provider_tizen.dart';

compute((Object? message) async {
  PathProviderPlugin.register();
  await getApplicationDocumentsDirectory();
}, null);
```

**Comment by swift-kim** [comment]
Will be fixed by https://github.com/flutter-tizen/flutter-tizen/pull/516.
