### ISSUE TITLE
TextField 'keyboardType: TextInputType.number' doesn't bring Numeric Keyboard

### ISSUE THREAD

**Issue by Juwols** [flutter-tizen/plugins#128]
Tested on [tizen-unified_20201020.1 rpi4](http://download.tizen.org/releases/milestone/tizen/unified/tizen-unified_20201020.1/images/standard/iot-headed-3parts-aarch64-rpi/) and [tizen-unified_20210614.2 mobile tm1](http://download.tizen.org/snapshots/tizen/unified/tizen-unified_20210614.2/images/standard/mobile-wayland-armv7l-tm1/).

Expected Result:
![image](https://user-images.githubusercontent.com/1029299/121996476-a7b72500-cde3-11eb-80d7-ddb1f6d32f9b.png)

Actual Result:
![image](https://user-images.githubusercontent.com/1029299/121996617-dfbe6800-cde3-11eb-8d20-fb3797edf1fa.png)

**Comment by swift-kim** [comment]
I looked into https://github.com/flutter-tizen/engine/pull/93 and I think the mapping is correct. You may want to use `TextInputType.phone` if you are expecting the former layout.

@bbrto21 How do you think?

**Comment by bwikbs** [comment]
Using ``ECORE_IMF_INPUT_PANEL_LAYOUT_NUMBERONLY`` might be worth considering at here.

**Comment by bwikbs** [comment]
Here is results from ``tm1``. It seems reasonable to me.
![dump_screen](https://user-images.githubusercontent.com/4053790/122158256-4d7f9800-cea7-11eb-9a65-4e68bc6f0423.png)

**Comment by bbrto21** [comment]
@swift-kim @bwikbs oh, looks good

**Comment by swift-kim** [comment]
Fixed by #115. The new engine will be released today.
