### ISSUE TITLE
[webview_flutter] Doesn't render after hot reload.

### ISSUE THREAD

**Issue by bbrto21** [flutter-tizen/plugins#132]
It is not clear whether the rendering is not occurring or the touch event is not being dispatched.
But it is always reproduced.

How to reproduce
- Run webview_flutter example
~- Do hot reload (shift + r)~
- Do restart (shift + r)
- scroll the screen

**Comment by bwikbs** [comment]
:ok_hand:

**Comment by bwikbs** [comment]
> Do hot reload (shift + r)

It's ``restart`` :smile:

**Comment by bbrto21** [comment]
closed by flutter-tizen/engine#119
