### ISSUE TITLE
New plugins candidates

### ISSUE THREAD

**Issue by swift-kim** [flutter-tizen/plugins#151]
I'm planning to extend these plugins for Tizen but not sure when I will.

Flutter Favorites:
- [ ] [google_sign_in](https://pub.dev/packages/google_sign_in) (Many Google packages, such as [googleapis](https://flutter.dev/docs/development/data-and-backend/google-apis) and Firebase plugins, depend on this plugin.)
- [x] [sqflite](https://pub.dev/packages/sqflite)
- [x] [geolocator](https://pub.dev/packages/geolocator) (or [location](https://pub.dev/packages/location))
- [ ] [flutter_local_notifications](https://pub.dev/packages/flutter_local_notifications) (Maybe?)

Just out of my personal interest:
- [ ] [flutter_webrtc](https://pub.dev/packages/flutter_webrtc)
- [ ] [youtube_player_flutter](https://pub.dev/packages/youtube_player_flutter) (Maybe?)

Not a plugin, but contains platform-specific code:
- [x] [flutter_native_splash](https://pub.dev/packages/flutter_native_splash)

**Comment by bwikbs** [comment]
I just looked at it for a moment. :smile: 

**Looks like we can do :**
- [ ] [sqflite](https://pub.dev/packages/sqflite)
- [ ] [geolocator](https://pub.dev/packages/geolocator) (or [location](https://pub.dev/packages/location))
- [ ] [flutter_local_notifications](https://pub.dev/packages/flutter_local_notifications)
- [ ] [flutter_webrtc](https://pub.dev/packages/flutter_webrtc)
- [ ] [youtube_player_flutter](https://pub.dev/packages/youtube_player_flutter) -> It's possible simply with ewk webview.

------

**Should be working?:**
- [ ] [lottie](https://pub.dev/packages/lottie)

------

**OMG!:**
- [ ] [google_sign_in](https://pub.dev/packages/google_sign_in) (Many Google packages, such as [googleapis](https://flutter.dev/docs/development/data-and-backend/google-apis) and Firebase plugins, depend on this plugin.)

------

It seems like a good plan. After short discussion, I think other developer will be able to participate too!

**Comment by swift-kim** [comment]
Oops. I somehow didn't notice lottie is a pure Dart package. I'll remove it from the list.

**Comment by bbrto21** [comment]
As you and I reviewed before, we know that sqflite is available on Tizen with the ffi implementation of sqflite(but a little extra work is needed). In addition to the previous review, are you considering adding a native implementation?

**Comment by swift-kim** [comment]
@bbrto21 As far as I remember the problem was with the use of path_provider functions on secondary isolates in the sqflite implementation. The issue will be resolved with [the next stable release of the Flutter SDK](https://github.com/flutter-tizen/plugins/issues/123#issuecomment-884780589). Is there any issue on top of that?

**Comment by bbrto21** [comment]
There is no other problem I know. when next flutter SDK released, I'll check it out again.

**Comment by swift-kim** [comment]
Notes on how to implement the google_sign_in plugin:

- [OAuth 2.0 for TV and Limited-Input Device Applications](https://developers.google.com/identity/protocols/oauth2/limited-input-device#allowedscopes) only supports limited scopes of Google APIs so it's not a practical option.
- Tizen's OAuth2 API uses a built-in browser (webview?) and I confirmed it is compatible with Google OAuth 2.0, but unfortunately the library is not available on TV devices.
- I'm not sure if there's another solution.

**Comment by yura2000** [comment]
Hi! Would be great to have a package with the ability to get a heart rate. https://docs.tizen.org/application/web/guides/sensors/ham/

**Comment by swift-kim** [comment]
@yura2000 Hi. I haven't personally tried out but there's a plugin called [**workout**](https://pub.dev/packages/workout) that supports the functionality.

Alternatively you can create a local copy of the [sensors_plus_tizen](https://github.com/flutter-tizen/plugins/tree/master/packages/sensors_plus) plugin and modify a few lines of its source code if you have some basic knowledge. Let me tell you the details if you're interested.

@bbrto21 I think it would be possible to extend the current sensors_plus_tizen plugin to support arbitrary types of sensors other than accelerometer and gyroscope (and also a custom measurement interval instead of a fixed interval of 1000 ms). Would you like to try?

**Comment by swift-kim** [comment]
Closing the issue. Please open a dedicated issue for a new plugin suggestion or request.
