### ISSUE TITLE
Update analysis_options.yaml

### ISSUE THREAD

**Issue by swift-kim** [flutter-tizen/plugins#161]
- 1st-party plugin implementations should use linter rules from https://github.com/flutter/plugins/blob/master/analysis_options.yaml.
- Some 1st-party plugins still depend on legacy options: https://github.com/flutter/plugins/blob/master/analysis_options_legacy.yaml
- 3rd-party plugins use their own linter rules. Copy analysis_options files from their repos.

**Comment by bbrto21** [comment]
[analyze.txt](https://github.com/flutter-tizen/plugins/files/7089491/analyze.txt)
