### ISSUE TITLE
WebViewController.loadUrl() fails with 

### ISSUE THREAD

**Issue by wiertel** [flutter-tizen/plugins#185]
I've been trying to use loadUrl() to change webview contents. But it fails with the error:
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(Invalid Arguments, Invalid Arguments, null, null)
```

I'm pretty sure it should be "url" instead of "viewType" here, as  this fixes the loadUrl().
https://github.com/flutter-tizen/plugins/blob/efe670a35d818a29731e079ac412ec0cd0a78ec6/packages/webview_flutter/tizen/src/webview.cc#L814

BTW. You might consider including more details in logs or result->Error(), it would make tracking issues easier

**Comment by bwikbs** [comment]
:scream: OMG! yor're right!
I wonder how this has been remained until now.

**Comment by wiertel** [comment]
Great. Thanks
