### ISSUE TITLE
Clean up issues which reported by analyze command

### ISSUE THREAD

**Issue by bbrto21** [flutter-tizen/plugins#194]
If you run flutter's analyze command, 557 issues are currently reported(including example codes).
I don't know if we have to solve all of these, however, some of these issues may need to be resolved.

[analyze.txt](https://github.com/flutter-tizen/plugins/files/7089491/analyze.txt)

**Comment by swift-kim** [comment]
Duplicate of https://github.com/flutter-tizen/plugins/issues/161?

**Comment by bbrto21** [comment]
@swift-kim Oh, you're right. I think this issue will be resolved by  #161 :) so I close this
