### ISSUE TITLE
Packages description is too short.

### ISSUE THREAD

**Issue by bbrto21** [flutter-tizen/plugins#210]
The following packages were given a low pub point because they had too short descriptions in pubspec.yaml

```
Add more detail to the description field of pubspec.yaml. Use 60 to 180 characters to describe the package,
what it does, and its target use case.
```
- [ ] sensors_tizen
- [ ] permission_handler_tizen
- [ ] audioplayers_tizen 
- [ ] flutter_tts_tizen
- [ ] wifi_info_flutter_tizen
- [ ] wakelock_tizen
- [ ] integration_test_tizen
- [ ] sensors_plus_tizen
- [ ] camera_tizen

**Comment by swift-kim** [comment]
The length doesn't really matter as long as the description provides enough information about the package.
```
The Tizen implementation of the xxxxxxxxx plugin.
```
should be enough in most cases.

**Comment by bbrto21** [comment]
Yes, you are right. However, for this reason, pub.dev does not mark our packages as compatible with the Flutter SDK :(

**Comment by swift-kim** [comment]
No, it's determined by whether the package has any Dart code. Most of Tizen plugins have only native implementations (`src`) but no `lib` directory so they are marked UNIDENTIFIED.

**Comment by bbrto21** [comment]
Oh, then it's purely about the score
![Screenshot from 2021-09-09 12-55-23](https://user-images.githubusercontent.com/1579532/132621584-dcd92be5-41f7-451e-a9cc-1930256e7e5c.png)

**Comment by swift-kim** [comment]
Closing due to the lack of justification.
