### ISSUE TITLE
[webview_flutter_lwe] webview should not have any fixed properties  

### ISSUE THREAD

**Issue by bbrto21** [flutter-tizen/plugins#211]
The following properties have fixed values, but you must choose them appropriately on runtime

- defaultFontName : "SamsungOneUI"
- locale : "ko-KR"
- timezoneID : "Asia/Seoul"

**Comment by swift-kim** [comment]
To get the current time zone:
https://docs.tizen.org/application/native/api/wearable/6.0/group__CAPI__BASE__UTILS__I18N__TIMEZONE__MODULE.html

To get the current locale info:
https://docs.tizen.org/application/native/api/wearable/6.0/group__CAPI__BASE__UTILS__I18N__ULOCALE__MODULE.html (also refer to the embedder's [`system_utils.cc`](https://github.com/flutter-tizen/engine/blob/flutter-2.10.1-tizen/shell/platform/tizen/system_utils.cc))

**Comment by swift-kim** [comment]
The LWE-based webview_flutter_tizen has been superseded by a new EWK-based implementation. Should we still track this issue?
