### ISSUE TITLE
[video_player] video freeze - audio ok

### ISSUE THREAD

**Issue by mhoeckner** [flutter-tizen/plugins#250]
Dear community

first of all - this is a very cool project! Nice work!

I tried to use the tizen video player on a new tizen 6.0 tv (QE50LS03AAUXXN)
I developed web based applications for tizen - so the platform is not new to me. Especially Tizen Studio
But my approach is, for future projects, to develop multi platform applications. 

Szenario: try to run the example provided in plugin video_player_tizen

Everything works fine - build - no errors

But the video does not start. Audio yes.

So I created an app on my own - for further testing 

Same problem - first frame show up - audio starts - video freeze

Tried to build with 4.0  and 6.0 wearable sdk 

Privileges added to manifest as described in documentation

Build says that no TV SDK can be found - maybe this is the problem? 
I tried to find the "TV SDK" - but I could not find it in package manager 
Tizen Package Manager -> Extensions -> TV Extensions 6.0 is installed

Tried ist with MP4 local, MP4 via WWW, HLS via WWW

Do you habe any idea why my video freezes?

Thank you in advance,
best regards,
Markus

=> flutter-tizen run      
Launching lib/main.dart on Tizen QE50LS03AAUXXN in debug mode...
TV SDK could not be found. Trying with Wearable SDK...
The TizenTVTest profile is used for signing.
Building a Tizen application in debug mode...                      33.8s
✓ Built build/tizen/tpk/com.example.xxx-1.0.0.tpk (25.6MB).
Installing build/tizen/tpk/com.example.xxx-1.0.0.tpk... 

=> flutter-tizen doctor -v
[✓] Flutter (Channel unknown, 2.5.1, on macOS 11.6 20G165 darwin-x64, locale en-GB)
    • Flutter version 2.5.1 at /Users/markushockner/development/flutter-tizen/flutter
    • Upstream repository unknown
    • Framework revision ffb2ecea52 (5 weeks ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

[✓] Tizen toolchain - develop for Tizen devices
    • Framework revision 6ba0011dac (9 days ago), 2021-10-13 12:11:25 +0900
    • Engine revision 7e8adde964
    • Tizen Studio 4.1.1 at /Users/markushockner/tizen-studio
    • .NET SDK 5.0.401 at /usr/local/share/dotnet/dotnet

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/markushockner/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/markushockner/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.61.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.27.0

[✓] Connected device (5 available)
    • Android SDK built for x86 (mobile) • emulator-5554                        • android-x86    •
      Android 8.1.0 (API 27) (emulator)
    • iPhone 12 Pro Max (mobile)         • 7048FD17-0C03-4535-9FCB-44D8B39FD9E0 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)                    • macos                                • darwin-x64     • macOS
      11.6 20G165 darwin-x64
    • Chrome (web)                       • chrome                               • web-javascript • Google
      Chrome 95.0.4638.54
    • Tizen QE50LS03AAUXXN (mobile)      • 192.168.80.204:26101                 • flutter-tester • Tizen
      6.0

**Comment by swift-kim** [comment]
This issue will be closed by https://github.com/flutter-tizen/plugins/pull/262 (`video_player_tizen` 2.3.0 will be released when the PR is merged).
