### ISSUE TITLE
[tizen_app_control] Integration test is failing

### ISSUE THREAD

**Issue by seungsoo47** [flutter-tizen/plugins#272]
@swift-kim Integration test for tizen_app_control is failing like following. Could you check the problems?

$ ./tools/run_command.py test --plugins tizen_app_control --platforms mobile-6.5
============= Testing for tizen_app_control (1/1) =============

00:00 +0: loading /tmp/flutter_tools.KGWRDJ/KLIKGX/tizen_app_control_test.dart                                                                                                                         Building a Tizen application in debug mode...
The project type of messageport_tizen plugin is "sharedLib", which is deprecated in favor of "staticLib".

00:21 +0: loading /tmp/flutter_tools.KGWRDJ/KLIKGX/tizen_app_control_test.dart
00:22 +0: loading /tmp/flutter_tools.KGWRDJ/KLIKGX/tizen_app_control_test.dart                                                                                                                         The public profile is used for signing.

00:34 +0: loading /tmp/flutter_tools.KGWRDJ/KLIKGX/tizen_app_control_test.dart
00:35 +0: loading /tmp/flutter_tools.KGWRDJ/KLIKGX/tizen_app_control_test.dart                                                                                                                         Building a Tizen application in debug mode...                      36.3s
✓ Built build/tizen/tpk/org.tizen.tizen_app_control_example-1.0.0.tpk (26.5MB).

00:37 +0: loading /tmp/flutter_tools.KGWRDJ/KLIKGX/tizen_app_control_test.dart                                                                                                                         Installing build/tizen/tpk/org.tizen.tizen_app_control_example-1.0.0.tpk...
01:03 +0: loading /tmp/flutter_tools.KGWRDJ/KLIKGX/tizen_app_control_test.dart
01:04 +0: loading /tmp/flutter_tools.KGWRDJ/KLIKGX/tizen_app_control_test.dart                                                                                                                            27.0s

01:09 +0: loading /tmp/flutter_tools.KGWRDJ/KLIKGX/tizen_app_control_test.dart
01:11 +1: Can receive request from platform
01:11 +2: Can find matching applications
01:11 +3: Can send and receive request
01:11 +4: Omit invalid extra data
01:22 +4: Can send and receive reply
01:22 +4 -1: Can send and receive reply [E]
TimeoutException after 0:00:10.000000: Test timed out after 10 seconds.
dart:isolate  _RawReceivePortImpl._handleMessage

01:22 +5 -1: Cannot find target applications
01:23 +5 -1: Can terminate service application
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure object was thrown running a test:
Expected: false
Actual: <true>

When the exception was thrown, this was the stack:
#4      main.<anonymous closure> (file:///home/leess/11_HDD/01_SRC/2020_Flutter/github/plugins/packages/tizen_app_control/example/integration_test/tizen_app_control_test.dart:111:5)
#5      main.<anonymous closure> (file:///home/leess/11_HDD/01_SRC/2020_Flutter/github/plugins/packages/tizen_app_control/example/integration_test/tizen_app_control_test.dart:110:52)
#6      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:176:29)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

This was caught by the test expectation on the following line:
file:///home/leess/11_HDD/01_SRC/2020_Flutter/github/plugins/packages/tizen_app_control/example/integration_test/tizen_app_control_test.dart line 111
The test description was:
Can terminate service application
════════════════════════════════════════════════════════════════════════════════════════════════════

01:23 +5 -2: Can terminate service application [E]
Test failed. See exception logs above.
The test description was: Can terminate service application

01:24 +5 -2: (tearDownAll)
01:24 +5 -2: Some tests failed.
============= TEST RESULT =============
FAILED: tizen_app_control ('mobile-6.5', 'TM1', '0000d82c00006200')
flutter-tizen test integration_test failed, see the output above for details.
Some tests failed.

**Comment by swift-kim** [comment]
It's a known issue and for this reason tizen_app_control is being excluded from CI integration testing.

https://github.com/flutter-tizen/plugins/blob/656fbab91616c1cf9b183b35ca7446dbd76e203a/.github/workflows/integration_test.yml#L46

The issue will not be fixed due to the fundamental limitation of flutter-tizen's `test` command. You can use the `drive` command to run the integration test instead.

@HakkyuKim By the way, why do we manage two separate lists of packages to include/exclude packages to/from integration testing? Can we use only one?

- https://github.com/flutter-tizen/plugins/blob/master/tools/recipe.yaml
- https://github.com/flutter-tizen/plugins/blob/656fbab91616c1cf9b183b35ca7446dbd76e203a/.github/workflows/integration_test.yml#L43-L46

**Comment by HakkyuKim** [comment]
The recipe file does not include/exclude plugins to test, it specifies which target platforms to test on  and the tool refers to to the file to create specific emulator profiles and Tizen versions.

https://github.com/flutter-tizen/plugins/blob/45896bddc2a7a870be8d25bd2494942aa884fab0/tools/commands/integration_test.py#L371-L385

A similar proposal was made by @bbrto21 [here](https://github.com/flutter-tizen/plugins/pull/243#discussion_r726772205), I haven't got a chance to work on it yet. When I do, I'll design towards listing all info in recipe.

**Comment by swift-kim** [comment]
@HakkyuKim But omitting a package or providing an empty list for a package in the recipe file effectively does the same thing as the `--exclude` option, right? I was thinking of eliminating this redundancy.

**Comment by swift-kim** [comment]
I read your comment about an empty list in the recipe file but I think you need to be more explicit about the "non specified" case if you really need it. For example, the following syntax may be used.

```yaml
plugins:
  audioplayers: any
  battery_plus: []
  camera: ["mobile-6.0"]
```

**Comment by HakkyuKim** [comment]
The "non-specified" case(empty list) doesn't have any practical meaning at this point, I remembered that I copied the entries from [device limitation table](https://github.com/flutter-tizen/plugins#device-limitations). At the time I wanted to point out that plugins with empty list cannot be tested on emulators, but I guess we're already filtering those out in the CI script.
We could just remove the entries with empty list, the result would be the same:

```
// recipe.yaml:
// plugins:
//   battery_plus: []

./tools/run_command.py test --plugins battery_plus --recipe recipe.yaml
FAILED: battery_plus 
Cannot find any testable targets.
Some tests failed.

// recipe.yaml:
// plugins:
//   nothing:

./tools/run_command.py test --plugins battery_plus --recipe recipe.yaml
FAILED: battery_plus 
Cannot find any testable targets.
Some tests failed.
```

**Comment by swift-kim** [comment]
@HakkyuKim I don't quite get what you want to say.

**Comment by HakkyuKim** [comment]
@swift-kim 
> By the way, why do we manage two separate lists of packages to include/exclude packages to/from integration testing? Can we use only one?

Right now, no because

> But omitting a package or providing an empty list for a package in the recipe file effectively does the same thing as the --exclude option, right? I was thinking of eliminating this redundancy.

is not true.

```yaml
# recipe.yaml
plugins:
  battery_plus: ["wearable-5.5"]
  camera: []
  device_info_plus: []
```

```bash
./tools/run_command.py test --exclude device_info_plus --recipe recipe.yaml
```

means:
- test `battery_plus` on wearable-5.5 emulator. -> ok
- test `camera` on None. -> error because no testing platforms are given.
- exclude `device_info_plus` -> ok because intentionally exclude testing. (The tool will not look for the entry in `recipe.yaml`)

> I haven't got a chance to work on it yet. When I do, I'll design towards listing all info in recipe.

Meant that maybe later recipe file can support something like:

```yaml
# recipe.yaml
plugins:
  battery_plus: ["wearable-5.5"]
  camera: []
  device_info_plus: exclude
```

As for now, we can remove all empty list entries in the recipe file because we're specifying them with `--exclude`(Not because empty list will exclude them from tests but because the tool will not look for the entry in `recipe.yaml`).

Does this answer your question?

**Comment by swift-kim** [comment]
> Meant that maybe **later** ...

I know the current status. What we're talking about here is that "later" design and I wanted to hear your opinion on my suggestion.

**Comment by HakkyuKim** [comment]
@swift-kim and I talked about the subject on company chat and concluded that it's simpler to just not have empty list/any. I'll remove them from `recipe.yaml`.
