### ISSUE TITLE
[network_info_plus] getWifiBroadcast() crashes if wifi is not connected

### ISSUE THREAD

**Issue by wiertel** [flutter-tizen/plugins#273]
Tried running the network_info_plus_example on device and the app crashed instantly.
There wifi is not connected. There are errors like this in dlog:
```
E/WIFI_MANAGER(165284): network_interface.c: __net_extract_connected_profile(1239) > There is no connected service
E/WIFI_MANAGER(165284): network_interface.c: net_get_connected_profile(3273) > Failed to get service(profile) list. Error [NET_ERR_NO_PROFILE]
```

**Comment by swift-kim** [comment]
Is this issue still being worked on? - https://github.com/flutter-tizen/plugins/pull/274#issuecomment-968456881

**Comment by swift-kim** [comment]
Tested on my watch (SM-R500) and the error seems to be already gone.
