### ISSUE TITLE
Integration test CI randomly fails when two workflows run simultaneously

### ISSUE THREAD

**Issue by HakkyuKim** [flutter-tizen/plugins#302]
Regression caused by changing the logic of handling the recipe file. I'll prepare a fix.

**Comment by swift-kim** [comment]
Another issue: The integration test intermittently fails even with https://github.com/flutter-tizen/plugins/pull/296 applied.

https://github.com/flutter-tizen/plugins/runs/4501024606?check_suite_focus=true
https://github.com/flutter-tizen/plugins/runs/4501007529?check_suite_focus=true

**Comment by HakkyuKim** [comment]
The issue seems to happen when two separate workflows run simultaneously, I'll do some testings locally to find the exact cause.

**Comment by swift-kim** [comment]
Is this resolved?

**Comment by HakkyuKim** [comment]
`--run-on-changed-packages` option is, but randomly failing when two runners simultaneously run is not.

**Comment by swift-kim** [comment]
Do we still have this problem?

**Comment by HakkyuKim** [comment]
I haven't seen this case for sometime, integration failures were always caused by disk space issue.
