### ISSUE TITLE
Target of URI doesn't exist error when importing 'package:tizen_app_control/app_control.dart'

### ISSUE THREAD

**Issue by Kyungeun-Park** [flutter-tizen/plugins#329]
I'd like to launch a Tizen native service application and monitor the its status from my Flutter application in Samsung TV(Tizen 6.5).

As one of several ways, I tried to use tizen_app_control plugin from https://github.com/flutter-tizen/plugins/tree/master/packages/tizen_app_control.

I added the dependency in the pubspec.yaml and imported the plugin package given the guide but the error occurs  about import as below.

" Target of URI doesn't exist: 'package:tizen_app_control/app_control.dart'.
  Try creating the file referenced by URI, or Try using a URI for a file that does exist. "

What should I do to solve this issue?

**Comment by swift-kim** [comment]
Hi.

If you're seeing the error in VS Code, you may need to press `Ctrl`+`Shift`+`P` and run `Pub: Get Packages` and `Dart: Restart Analysis Server` to restart the Dart analysis server.

**Comment by Kyungeun-Park** [comment]
I solved this issue as your guide. Thank you. :)
