### ISSUE TITLE
[flutter_blue_tizen] Unit testing with google mock

### ISSUE THREAD

**Issue by JRazek** [flutter-tizen/plugins#335]
flutter_blue_tizen plugin is ready for tests. Repository is currently [here](https://github.com/JRazek/flutter_blue_tizen).

Since the plugin uses Bluetooth communication, it is necessary to either use another device for testing or mock it. 
We are planning to use google mock framework for testing. 
Mocking would help in simulation of different scenarios in unit tests that we are going to prepare. 
By using unit tests we would be able to ensure that any patch in a code doesn't break the rest of it, but it will surely take some time to write them. 

To achieve our goal I've been trying to separate a `main()` function implemented by the `flutter-tizen` framework in the  [runner.cc](https://github.com/flutter-tizen/flutter-tizen/blob/master/templates/ui-app/cpp/src/runner.cc) file, simply use a plugin as a library and test it by calling method channel. 
That's my current `main.cc` file that I'm trying to build:
```cpp
#include <iostream>
#include <flutter.h>

class App : public FlutterApp {
 public:
  bool OnCreate() {
    if (FlutterApp::OnCreate()) {

    }
    return IsRunning();
  }
};

auto main(int argc, char *argv[]) -> int{
    App app;
    app.SetDartEntrypoint("serviceMain");
    return app.Run(argc, argv);
}
```
I am linking to it following files generated by the flutter-tizen:
```
flutter_engine
flutter_tizen_tv
flutter_plugins
embedding_cpp
```
Linker gives me errors about missing libraries such as
 ```
tdm_client_create
eglGetCurrentDisplay
eglCreateWindowSurface
wl_proxy_marshal
```
etc.
Where I can find libraries containing definitions of these symbols?

I was given an information that you usually don't write unit tests for the native part and just rely on integration tests. 
I believe that it will be hard to catch all the issues using integration tests in case of Bluetooth plugin.

Should we write unit tests at all?

**Comment by swift-kim** [comment]
cc @pkosko @wiertel

**Comment by swift-kim** [comment]
FYI) Some Windows and Linux packages in flutter/plugins have native unit tests. (Example: [url_launcher_windows_test](https://github.com/flutter/plugins/tree/main/packages/url_launcher/url_launcher_windows/windows/test))

Apparently they use CMake to build tests, but as far as I know the Tizen CLI builder doesn't natively support CMake, so you will need to create some build configuration to build a test executable (e.g. you may start with writing a `CMakeLists.txt` that depends on a public Tizen rootstrap installed on your local hard drive, or just create a `project_def.prop` for the test project and somehow create a test executable from it). I think you've already done this according to your description, although I don't know how you did.

Regarding your question, our native package builder sets the `--unresolved-symbols=ignore-in-shared-libs` linker flag (as you can see in [package.dart](https://github.com/flutter-tizen/flutter-tizen/blob/5bcb2eb3c440b1c81e5a60aabb876b07913d0ad6/lib/build_targets/package.dart#L332)) to avoid resolving symbols in libraries that can be loaded at runtime. Have you tried this option?

**Comment by JRazek** [comment]
Hello, I tried it and it compiled with `--unresolved-symbols=ignore-in-shared-libs` flag :)
