### ISSUE TITLE
[webview_flutter_lwe] Crash when navigating to specific URL on emulator

### ISSUE THREAD

**Issue by swift-kim** [flutter-tizen/plugins#339]
Issue 1. App crash

1. Set the example app's `initialUrl` to either https://stackoverflow.com or https://map.kakao.com.
2. Run.

Issue 2. Visual artifacts (residual image)

1. Set the `initialUrl` to https://map.naver.com (or any other).
2. Run.
3. Once the webview finishes to load the site, terminate the app.
4. Set the `initialUrl` to https://www.google.com (or any other).
5. Run again.

![T-samsung-6 0-x86-2022-03-16-134414](https://user-images.githubusercontent.com/40190588/158519126-90fc0ed8-28ce-4659-a5b0-18e759b216e4.png)
![T-samsung-6 0-x86-2022-03-16-130658](https://user-images.githubusercontent.com/40190588/158519167-9354e44c-04c5-48df-9892-179012ea4398.png)

Issue 3. Images not displayed

1. Set the `initialUrl` to https://www.naver.com.
2. Run and observe that images on the site (ads and etc.) are not displayed properly.

![T-samsung-6 0-x86-2022-03-16-135038](https://user-images.githubusercontent.com/40190588/158519184-8cb158d1-ac05-4a82-b9f3-dde4a40b8d6a.png)

Issue 4. Output resolution

As you can see in the above screenshots, texts are too unclear to read.

@seungsoo47 @bwikbs @bbrto21

**Comment by bwikbs** [comment]
@swift-kim 
Wow 😱  it's only been a few hours since it merge, but you've already tried it.

At a glance, some seems to be related plug-in, and the other seem to be lwe issues.
We will solve the plugin-related issues first and then solve the lwe later.

I'll let you know here whenever something gets resolved a little bit.

**Comment by bbrto21** [comment]
> * Set the example app's `initialUrl` to either https://stackoverflow.com or https://map.kakao.com.

It doesn't seem to crash anymore. I just tested it with #456.

**Comment by swift-kim** [comment]
@bbrto21 I tried the patch but the app still intermittently crashes on TV emulator when `initialUrl` is set to https://map.kakao.com.

**Comment by bbrto21** [comment]
Oh, you're right... There seems to be another problem lurking :cry:

**Comment by swift-kim** [comment]
The app also crashes during page loading when I click the "Visit dart.dev" button in the flutter.dev page. I tested on a mobile emulator.
