### ISSUE TITLE
Avoid use of shared method channels

### ISSUE THREAD

**Issue by swift-kim** [flutter-tizen/plugins#348]
Shared method channels (default impl. of platform interfaces) are not going to be actively maintained in flutter/plugins (although they are not being deprecated immediately), so we need to stop using them in our packages and instead, add explicit Dart implementations.

Context:
- https://docs.flutter.dev/go/platform-channels-in-federated-plugins
- https://github.com/flutter/flutter/issues/68498
- https://github.com/flutter/flutter/issues/94224

Packages that need migration:
- [x] video_player_tizen
  - This might ease migrating the package to the plusplayer-based implementation which will require more Tizen-specific functions to be added on top of the existing platform interface. (@xuelian-bai Please provide some details if you have any.)
  - May depend on https://github.com/flutter-tizen/plugins/issues/347.
- [x] image_picker_tizen
- [x] camera_tizen

Not applicable (already migrated):
- google_maps_flutter_tizen
- google_sign_in_tizen
- path_provider_tizen
- shared_preferences_tizen
- url_launcher_tizen
- webview_flutter_tizen

**Comment by stuartmorgan** [comment]
> * May depend on [[pigeon] Add  C++ support #347](https://github.com/flutter-tizen/plugins/issues/347).

This is only the case if you specifically want to use Pigeon. Per-package method channels means that everything about the communication channel—including whether or not to use Pigeon—is up to each implementation package to decide, regardless of what other platform implementations do.
