### ISSUE TITLE
log.h defines

### ISSUE THREAD

**Issue by JRazek** [flutter-tizen/plugins#365]
Hello, I noticed that the file generated by `flutter-tizen` `log.h`, that is commonly used for logging, uses following defines
```cpp
#define __LOG_H__
#define __MODULE__
```
As far as I know it is considered undefined behavior according to C++ [standard](https://eel.is/c++draft/lex.name#3). 
```
Each identifier that contains a double underscore __ or begins with an underscore followed by an uppercase letter is reserved to the implementation for any use.
```

Is there any reason for this naming convention?

**Comment by swift-kim** [comment]
As far as I remember the style used by the file originated from old Tizen platform code, and thus does not follow our new standard (Google style guide). In fact, use of preprocessor macros is discouraged by the style guide. The template code aims to provide a **simple** and **uniform** logger implementation that can be easily understood by anybody across all plugin packages. If you think the template is outdated or needs improvement, please file PRs in both repositories (flutter-tizen and plugins).

p.s. The page you linked doesn't seem to be a universal C++ standard. There's even no author information.

**Comment by swift-kim** [comment]
If you're not going to fix, I'll close this issue.
