### ISSUE TITLE
Plugin사용중 Tizen Privilege문의

### ISSUE THREAD

**Issue by yman-son** [flutter-tizen/plugins#367]
안녕하세요.

Plugin guide page를 살펴보면 tizen-manifest.xml에 privilege를 선언하라는 부분을 볼 수 있습니다. 
https://github.com/flutter-tizen/plugins/tree/master/packages/tizen_app_manager#required-privileges

Tizen Privilege는 Level이 있으며, 이는 Public, Partner, Platform으로 나눠져 있습니다. 
https://www.tizen.org/privilege?langredirect=1
이 Level에 따라서 패키징시에 사용하는 인증서의 Level이 달라지게 될텐데요. 

flutter-tizen에는 이런 부분에 대한 언급이 없어서 질문을 드리게 됐습니다. 

Level관련없이 privilege를 선언하면 인증서 level관련 없이 패키징 및 사용이 가능하도록 되어 있는 것인지?
높은 level의 privilege를 사용시에는 Tizen studio에 인증서를 level에 맞게 셋팅을 해야 하는지?
Plugin guide page에 privilege level에 대한 언급을 추가할 계획이신지 등에 대해 검토하신 내용이 있으시면 공유 부탁 드립니다. 

감사합니다.

**Comment by swift-kim** [comment]
현재 이 repo의 패키지들 중에서 partner 또는 platform level privilege를 요구하는 API는 `AppRunningContext.terminate` 뿐인 걸로 알고 있으며 해당 [API 문서](https://pub.dev/documentation/tizen_app_manager/latest/app_manager/AppRunningContext/terminate.html) ([코드](https://github.com/flutter-tizen/plugins/blob/1becaddcf442da0d2a858f753d02e832b755eaca/packages/tizen_app_manager/lib/app_manager.dart#L214-L215))에 간략히 언급되어 있습니다. (partner가 아니라 platform인 듯한데 잘못 표기된 것 같습니다.)

Partner level privilege 사용에 대한 가이드는 따로 제공하고 있지 않습니다. `flutter-tizen run` 커맨드 사용 시 Certificate Manager에서 active로 설정하신 profile이 자동으로 사용됩니다.
