### ISSUE TITLE
Publish packages automatically after merge

### ISSUE THREAD

**Issue by swift-kim** [flutter-tizen/plugins#378]
Currently the publication is manually done by human. We may add a workflow to the CI that does the following things.

- Check for packages that need publishing (by comparing versions of local packages and packages on pub.dev).
- Set up pub.dev credentials (`accessToken` and `refreshToken`).
- Run `pub publish --dry-run` for each package on pull request.
- Run `pub publish` for each package on push.

Basic idea: https://medium.com/evenbit/publishing-dart-packages-with-github-actions-5240068a2f7d

**Comment by swift-kim** [comment]
We could make this a tool command similarly to flutter_plugin_tools' [`PublishPluginCommand`](https://github.com/flutter/plugins/blob/main/script/tool/lib/src/publish_plugin_command.dart).

We can't use their code as it is, and need to make some modifications. Especially we don't tag our releases, so related checks should be skipped.

**Comment by HakkyuKim** [comment]
I also looked into this a few days ago, I'll work on this.
