### ISSUE TITLE
[audioplayers] Fix a crash issue on TV

### ISSUE THREAD

**Issue by HakkyuKim** [flutter-tizen/plugins#382]
~~Calling `player_destroy()` in the `OnPlayCompletedcallback` function crashes the player module on TV. Instead, `player_unprepare()` seems like a more appropriate function to call in `Release()` according to the documentation of [ReleaseMode](https://github.com/bluefireteam/audioplayers/blob/a9d2d01b8aaab1a57437291c446913957f845224/packages/audioplayers_platform_interface/lib/api/release_mode.dart#L9).~~ See commit message in https://github.com/flutter-tizen/plugins/pull/406/commits/10ea3dd7f0f996c8a4825242414c153beaf3157b for reasons why some issues occurred on TV devices.

~~As there are quite a bit of change in audioplayers 1.0.0,~~ This issue may be fixed when supporting audioplayers 1.0.0 version.

**Comment by HakkyuKim** [comment]
@wanchao-xu 
Did [limitations on TV](https://github.com/flutter-tizen/plugins/tree/master/packages/audioplayers#limitations) only happen on physical devices, or also in emulators?

**Comment by wanchao-xu** [comment]
> @wanchao-xu Did [limitations on TV](https://github.com/flutter-tizen/plugins/tree/master/packages/audioplayers#limitations) only happen on physical devices, or also in emulators?

Both physical devices and emulators.
