### ISSUE TITLE
Update analysis_options.yaml

### ISSUE THREAD

**Issue by swift-kim** [flutter-tizen/plugins#389]
Recently in the upstream repo, some updates have been made to the analysis_options.yaml file and example apps. We need to sync our code again accordingly.

https://github.com/flutter/plugins/commits/main/analysis_options.yaml

**Comment by swift-kim** [comment]
@bbrto21 @bwikbs @seungsoo47 Could you remove references to `analysis_options_legacy.yaml` in `camera_tizen`, `google_maps_flutter_tizen`, and `webview_flutter_tizen` as well? You will first need to resync all their Dart code (the example app and etc.) and update app-facing and platform interface packages as I've done in https://github.com/flutter-tizen/plugins/pull/392.

**Comment by bbrto21** [comment]
@swift-kim 
I'll check `camera_tizen` but depending on my work priority, this may be processed late.
Is that okay?

**Comment by swift-kim** [comment]
@bbrto21 That's okay. This whole work is a quite demanding task and my expectation is that it will take at least a month to close this issue.
