### ISSUE TITLE
[path_provider] Tizen SDK doesn't zip data directory.

### ISSUE THREAD

**Issue by HakkyuKim** [flutter-tizen/plugins#414]
See https://github.sec.samsung.net/RS-TizenStudio/home/issues/238#issuecomment-1515563 (internal Github).

According to the comment, `getApplicationSupportDirectory` and `getApplicationDocumentsDirectory` should now return `res` directory.

**Comment by swift-kim** [comment]
I don't even understand what you're trying to do. Why are you trying to include the directory to TPK?

https://docs.tizen.org/application/native/tutorials/details/io-overview/

https://pub.dev/documentation/path_provider/latest/path_provider/getApplicationSupportDirectory.html

https://pub.dev/documentation/path_provider/latest/path_provider/getApplicationDocumentsDirectory.html

As a side note, Tizen doesn't have a concept of "user data" directory so the path returned by `getApplicationDocumentsDirectory` on Tizen is technically misleading. We might need to unsupport the API and only support `getApplicationSupportDirectory` in the future.

**Comment by HakkyuKim** [comment]
Client apps of `google_sign_in` requires placing "non user-generated private data of the application" file (`client_id` and `client_secret`) in the app. According to the [documentation](https://docs.tizen.org/application/native/tutorials/details/io-overview/), the file should be placed in the `data` directory where its path is returned by the `app_get_data_path` API. But files in `data` directory are no longer packaged inside tpk and therefore not installed to target. Consequently, both `getApplicationSupportDirectory` and `getApplicationDocumentsDirectory` returns a path to an empty directory at runtime.

This is the comment from the SDK team:
> The current tpk structure allows only these folders. so at the root level, we can have only these folders.
>
> inc: Default folder for included header files
> res: Folder for resource files used by the application only
> shared: Folder for resource files to be shared with other applications
> src: Folder for source code files
> lib: Folder for external library files
> tizen-manifest.xml: Manifest file used by the platform to install and launch the application,

I assumed the documentation was outdated, so this issue is proposing that `getApplicationSupportDirectory` and `getApplicationDocumentsDirectory` return `res` directory which serves a similar purpose with the (now deprecated?) `data` directory.
