### ISSUE TITLE
[video_player] Streaming over network is not working

### ISSUE THREAD

**Issue by avinash-gotluru** [flutter-tizen/plugins#422]
this is what I'm getting when I try to initialize the video controller In initstate().

[E] [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(Player error, Streaming connection failed, null, null)

could you please help me with the issue?

**Comment by wanchao-xu** [comment]
The log has no useful information, could you share all the log to us?

**Comment by wanchao-xu** [comment]
From the error infomation "Streaming connection failed", it seems the network is disconnected, please check the network is ok first.

**Comment by avinash-gotluru** [comment]
I'm running the plugin example without any change in the code.

**Comment by avinash-gotluru** [comment]
avinashgo@MTLP-2478 example % flutter-tizen devices
3 connected devices:

macOS (desktop)               • macos              • darwin-x64     • macOS 12.5 21G72 darwin-x64
Chrome (web)                  • chrome             • web-javascript • Google Chrome 104.0.5112.79
Tizen UA75BU8000KXXL (mobile) • 10.10.39.129:26101 • flutter-tester • Tizen 6.5
avinashgo@MTLP-2478 example % flutter-tizen run    
Running "flutter pub get" in example...                          2,654ms
Launching tizen/flutter/generated_main.dart on Tizen UA75BU8000KXXL in debug mode...
TV SDK could not be found. Trying with Wearable SDK...
The Avinash profile is used for signing.
Building a Tizen application in debug mode...                      48.0s
✓ Built build/tizen/tpk/org.tizen.video_player_tizen_example-1.0.0.tpk (31.6MB).
Installing build/tizen/tpk/org.tizen.video_player_tizen_example-1.0.0.tpk...        26.5s
[E] [WARN][(tid:2867)(_wl_egl_tizen_get_tizen_private)] Should create tpl_surface with this wl_egl_window first.
[WARN][(tid:2867)(_wl_egl_tizen_get_tizen_private)] All wl_egl_window_tizen APIs will be ignored.
[I] [EGL_DBG]: eglGetDisplay:2124, Winsys [tizen] path
[I] [EGL_DBG]: eglInitialize:2260, [Novatek][Mali-G52][libmali.so][rel]: Rev: r23p0, Winsys: <tizen + fbdev> SHA [0ef4704f]
[E] [WARN][(tid:2867)(wl_egl_window_tizen_set_buffer_transform)] wl_egl_window(0xa487d8) wl_output_transform(0) already rotated
[E] [WARN][(tid:2867)(wl_egl_window_tizen_set_window_transform)] wl_egl_window(0xa487d8) window_transform(0) already rotated
Syncing files to device Tizen UA75BU8000KXXL...                     74ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

💪 Running with sound null safety 💪

An Observatory debugger and profiler on Tizen UA75BU8000KXXL is available at: http://127.0.0.1:54442/FWJDMnlf6wc=/
[E] [WARN][(tid:2867)(wl_egl_window_tizen_set_buffer_transform)] wl_egl_window(0xa487d8) wl_output_transform(0) already rotated
[E] [WARN][(tid:2867)(wl_egl_window_tizen_set_window_transform)] wl_egl_window(0xa487d8) window_transform(0) already rotated
The Flutter DevTools debugger and profiler on Tizen UA75BU8000KXXL is available at: http://127.0.0.1:9100?uri=http://127.0.0.1:54442/FWJDMnlf6wc=/
[E] [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(Player error, Streaming connection failed, null, null)

**Comment by avinash-gotluru** [comment]
@wanchao-xu  could you please check the logs that I have shared?

**Comment by swift-kim** [comment]
Does your TV have an Internet connection?

**Comment by avinash-gotluru** [comment]
Yes @swift-kim

**Comment by avinash-gotluru** [comment]
I have check with the connectivity_plus here are the logs

Restarted application in 2,956ms.
[I] flutter: Running on UA75BU8000KXXL
[I] flutter: wifi

**Comment by avinash-gotluru** [comment]
here is the manifest .xml

`<?xml version="1.0" encoding="utf-8"?>
<manifest package="com.example.mouritv_tizen" version="1.0.0" api-version="4.0" xmlns="http://tizen.org/ns/packages">
    <profile name="common"/>
    <ui-application appid="com.example.mouritv_tizen" exec="Runner.dll" type="dotnet" multiple="false" nodisplay="false" taskmanage="true" api-version="4">
        <label>mouritv_tizen</label>
        <icon>ic_launcher.png</icon>
        <metadata key="http://tizen.org/metadata/prefer_dotnet_aot" value="true"/>
    </ui-application>
    <tv-info api-version="8.8.0">
        <infolink>T-INFOLINK2021-1000</infolink>
    </tv-info>
    <feature name="http://tizen.org/feature/screen.size.all"/>
    <privileges>
        <privilege>http://tizen.org/privilege/mediastorage</privilege>
        <privilege>http://tizen.org/privilege/externalstorage</privilege>
        <privilege>http://tizen.org/privilege/internet</privilege>
        <privilege>http://tizen.org/privilege/network.get</privilege>
    </privileges>
</manifest>
`

**Comment by swift-kim** [comment]
If you didn't modify the example app code, could you verify the connection by replacing `_App()` at line 15 with `Image.network('https://picsum.photos/250?image=9')`? i.e.

```dart
void main() {
  runApp(
    MaterialApp(
      home: Image.network('https://picsum.photos/250?image=9'),
    ),
  );
}
```

An image will be shown if your device has an Internet connection. Otherwise a black screen will be displayed.

**Comment by avinash-gotluru** [comment]
![MicrosoftTeams-image (19)](https://user-images.githubusercontent.com/83296096/183893515-6c346421-b633-4484-8e24-29067863278a.png)

**Comment by avinash-gotluru** [comment]
@swift-kim  Any suggestions?
I hope the network is not an issue, I believe

**Comment by swift-kim** [comment]
Unfortunately I don't have any idea. @flutter-tizen/maintainers Do you have one?

**Comment by wanchao-xu** [comment]
The error is occurred when play network video "https://flutter.github.io/assets-for-api-docs/assets/videos/bee.mp4", could you check "https://flutter.github.io/assets-for-api-docs/assets/videos/bee.mp4" can be played by browser?

**Comment by avinash-gotluru** [comment]
@wanchao-xu the network video is working in the browser.

**Comment by wanchao-xu** [comment]
> @wanchao-xu the network video is working in the browser.

Do you use TV browser to open network video?

And could you share the software version of TV? Press 'MENU' key of controller -> Select 'Support' -> Select 'About This TV', please share this information, we are trying to reproduce this issue.

**Comment by karthik-reddy-8** [comment]
@wanchao-xu, is this info enough, or do you want any other.

![samsung-tv-version](https://user-images.githubusercontent.com/79559316/184806450-66411116-f4ec-4c95-855a-74d63187f209.jpeg)

**Comment by avinash-gotluru** [comment]
![MicrosoftTeams-image (25)](https://user-images.githubusercontent.com/83296096/185383082-b7490d56-55de-41ff-b07e-4b05bc7b938c.png)
![MicrosoftTeams-image (24)](https://user-images.githubusercontent.com/83296096/185383099-d438a543-f13a-4ca9-bda5-4e0d287caa12.png)
![MicrosoftTeams-image (23)](https://user-images.githubusercontent.com/83296096/185383105-91b084c8-3d8a-479f-b1d3-0f9eec60a2a5.png)
![MicrosoftTeams-image (22)](https://user-images.githubusercontent.com/83296096/185383108-ed3626e0-c7ee-462d-8fe7-581dd5bfff11.png)
![MicrosoftTeams-image (21)](https://user-images.githubusercontent.com/83296096/185383116-cacbeb92-8d38-43b8-8ccc-0ef4b7991a87.png)
![MicrosoftTeams-image (20)](https://user-images.githubusercontent.com/83296096/185383124-60764875-7542-4b65-b750-6795f3db2398.png)
![MicrosoftTeams-image (19)](https://user-images.githubusercontent.com/83296096/185383129-90c2c37b-1885-4805-84aa-6a374a6e3f5b.png)
![MicrosoftTeams-image (18)](https://user-images.githubusercontent.com/83296096/185383141-e5dfbe22-aa0b-492b-b67f-6eb03da3a17f.png)

**Comment by avinash-gotluru** [comment]
@wanchao-xu These are all the TVs I have, please check with them and let me know if you need anything else.

**Comment by wanchao-xu** [comment]
We tried to run video player example on TV which same as yours, and this bug can't be reproduced.
Does the video player example can play asset video? If the asset video can be played, this problem may be caused by network.

**Comment by avinash-gotluru** [comment]
@wanchao-xu yes the video player is able to play asset video

**Comment by avinash-gotluru** [comment]
@wanchao-xu  Can you please help us on this ?

**Comment by wanchao-xu** [comment]
Could you change the network video to 'http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4' and test it work or not?
I want to verify whether this isuuse caused by 'https'.

```
--- a/packages/video_player/example/lib/main.dart
+++ b/packages/video_player/example/lib/main.dart
@@ -217,7 +217,7 @@ class _BumbleBeeRemoteVideoState extends State<_BumbleBeeRemoteVideo> {
   void initState() {
     super.initState();
     _controller = VideoPlayerController.network(
-      'https://flutter.github.io/assets-for-api-docs/assets/videos/bee.mp4',
+      'http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4',
       closedCaptionFile: _loadCaptions(),
       videoPlayerOptions: VideoPlayerOptions(mixWithOthers: true),
     );
```

**Comment by avinash-gotluru** [comment]
@wanchao-xu I will check with it and let you know about it.

**Comment by avinash-gotluru** [comment]
@wanchao-xu the video is working fine with the HTTP

**Comment by avinash-gotluru** [comment]
But with HTTPS not working could you please help us achieve them @wanchao-xu. any suggestions from your end

**Comment by wanchao-xu** [comment]
It seems some certification is invalid. Please try to reset pricacy of TV, then re-test the video player example with https video.

![20220826_092119](https://user-images.githubusercontent.com/32251018/186796335-6a689db2-cb33-459b-b14f-96c8839bd33f.jpg)

**Comment by avinash-gotluru** [comment]
@wanchao-xu Do you have any idea how to implement the remote control for navigation and clicking the buttons inside the application

**Comment by wanchao-xu** [comment]
The flutter app support clicking the buttons, and I'm not clear what scene do you want.

**Comment by avinash-gotluru** [comment]
@wanchao-xu I have tried resetting the tv, so that I can use https:// for videos. But unfortunately, we are unable to render the video after resetting the TV. is there a way that I can install those certificates manually?

**Comment by wanchao-xu** [comment]
> 

Do you mean flutter video player can't play 'https://' video after reset 'General & Privacy'?

**Comment by wanchao-xu** [comment]
> @wanchao-xu I have tried resetting the tv, so that I can use https:// for videos. But unfortunately, we are unable to render the video after resetting the TV. is there a way that I can install those certificates manually?

Do you mean flutter video player can't play 'https://' video after reset 'General & Privacy'?

**Comment by avinash-gotluru** [comment]
Yes, it's still remain the same

**Comment by Konda-Koushik** [comment]
> > @wanchao-xu I have tried resetting the tv, so that I can use https:// for videos. But unfortunately, we are unable to render the video after resetting the TV. is there a way that I can install those certificates manually?
> 
> Do you mean flutter video player can't play 'https://' video after reset 'General & Privacy'? Is the error 'Streaming connection failed'?
> 
> ```
> [E] [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(Player error, Streaming connection failed, null, null)
> ```

yes @wanchao-xu

**Comment by wanchao-xu** [comment]
@Konda-Koushik , @avinash-gotluru  This problem may be caused by proxy, does the tv use proxy?

**Comment by avinash-gotluru** [comment]
How do we check for proxy, Can you please help us with it ?

**Comment by wanchao-xu** [comment]
@avinash-gotluru, You can check the the ip setting, and check the DNS.

**Comment by awsmoviesstore** [comment]
[E] [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(Player error, Streaming connection failed, null, null) ,

i have same error. how to fix. network image is show.

**Comment by xuelian-bai** [comment]
@awsmoviesstore which plugin did you use? Which sample did you run? You get this error for all videos?
