### ISSUE TITLE
VLC lib built for ARMEL

### ISSUE THREAD

**Issue by nassimus26** [flutter-tizen/plugins#443]
Hi, I am using the [dart_vlc ](https://pub.dev/packages/dart_vlc/example) plugin, is it possible to port it to Tizen ? it's rely on the libvlc 3.x for android , I found this old project [vlc-tizen](https://code.videolan.org/videolan/vlc-tizen) , and they don't provide a built libraries.

**Comment by swift-kim** [comment]
Hi.

Maybe you can build by yourself. The [VLC](https://github.com/videolan/vlc) player is licensed under GPLv2 and we don't have any plan to provide pre-built libraries.
