### ISSUE TITLE
[audioplayers] Unhandled Exception: Player interrupted.

### ISSUE THREAD

**Issue by avinash-gotluru** [flutter-tizen/plugins#445]
here is the method I'm trying to call the audio player

audioPlay() async {
    final player = AudioPlayer();
    await player.setReleaseMode(ReleaseMode.loop);
    await player.play(
        UrlSource(
            'https://github.com/avinash-gotluru/avinash-gotluru/blob/main/moment.mp3?raw=true'));
  }

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Player interrupted.
#0      MethodChannelAudioplayersPlatform._doHandlePlatformCall (package:audioplayers_platform_interface/method_channel_audioplayers_platform.dart:174:9)
#1      MethodChannelAudioplayersPlatform.platformCallHandler (package:audioplayers_platform_interface/method_channel_audioplayers_platform.dart:147:7)
#2      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:536:55)
#3      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:529:34)
#4      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:387:35)
#5      _invoke2 (dart:ui/hooks.dart:186:13)
#6      _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
#7      _Channel.push (dart:ui/channel_buffers.dart:132:31)
#8      ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
#9      PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:599:22)
#10     _dispatchPlatformMessage (dart:ui/hooks.dart:89:31)
```

**Comment by swift-kim** [comment]
Apparently the error message is from this line: https://github.com/flutter-tizen/plugins/blob/5dfaa17ee76c74eabe6554c75bd607e6883d060e/packages/audioplayers/tizen/src/audio_player.cc#L406

Should this actually be treated as an error? @wanchao-xu Do you know anything about this?

**Comment by avinash-gotluru** [comment]
@swift-kim can you help us with the issue?

**Comment by swift-kim** [comment]
What if you just ignore the exception? Does the player play anything? If not, can the player play a local audio file instead of a URL?

Also which device are you testing the app on?

**Comment by xuelian-bai** [comment]
We can't connect to this url on TV, but after downloading this audio file, it can play as local audio file
