### ISSUE TITLE
add support video_player

### ISSUE THREAD

**Issue by AhmedWahdanZ** [flutter-tizen/plugins#45]
add support to video_player
https://pub.dev/packages/video_player

**Comment by AhmedWahdanZ** [comment]
‎55"‎ UHD 4K Curved Smart TV MU7350 Series 7

**Comment by swift-kim** [comment]
The device is not supported according to https://github.com/flutter-tizen/flutter-tizen#supported-devices. (Or you need to establish a special partnership with Samsung's VD division to get your app signed on their signing server. I don't know how to do so.)
