### ISSUE TITLE
Question: [google_maps_flutter] Can't open map.html

### ISSUE THREAD

**Issue by zCode93** [flutter-tizen/plugins#453]
What's the reason for having "Can't open page file: ................/res/flutter_assets/assets/map.html"

Application is being tested on a real TV 6.5
map.html is added, with an API key, Maps JavaScript API is enabled.

**Comment by bbrto21** [comment]
First of all, I'm sorry for the inconvenience, but I can't reproduce it. could you share more detailed situation?
and I also have a few questions.
Do you get the same error using the TV emulator?
Is this the result of running the [example of google_maps_flutter](https://github.com/flutter-tizen/plugins/tree/master/packages/google_maps_flutter/example)?
