### ISSUE TITLE
Where should Firebase related code go?

### ISSUE THREAD

**Issue by wiertel** [flutter-tizen/plugins#473]
Where should I add first Firebase plugins, here in flutter-tizen/plugins or in a new repository under flutter-tizen org?

This is about code related to flutter-tizen/flutter-tizen#353. We have first 3 plugins (core, auth, functions) and would like to share it. Adding them to flutter-tizen/plugins would make it easier to publish now. Having them in separate repo would require additional setup (Actions, publishing).
Current code is heavily dependent on https://github.com/invertase/flutterfire_desktop. There will be more plugins in time. The implementation might change too in favor of more directly implementing relevant platform interfaces .

**Comment by swift-kim** [comment]
Preferably in this repo, if there's no other special reason.

**Comment by HakkyuKim** [comment]
> Having them in separate repo would require additional setup (Actions, publishing).

I'm also in favor of adding in this repo.
