### ISSUE TITLE
[get_mac_address] A tizen implementation to get the MAC address of the device

### ISSUE THREAD

**Issue by Wian-TMC** [flutter-tizen/plugins#507]
Seeing as the Tizen ID for a device can be reset by resetting the TV or device, we need a more robust unique identifier for the Device, such as the MAC address. This will help identify devices and linking them to users.

**Comment by swift-kim** [comment]
Tizen ID is a randomly-generated string based on libuuid and it doesn't seem to survive factory reset as you realized. Instead, you can get the MAC address of your device's network adapter (Wi-Fi or ethernet) as follows.

1. Add the following privilege to your app's `tizen-manifest.xml`.
   ```xml
   <privileges>
       <privilege>http://tizen.org/privilege/network.get</privilege>
   </privileges>
   ```

2. Add the following dependencies to your app's `pubspec.yaml`.
   ```yaml
   dependencies:
     ffi: ^2.0.1
     tizen_interop: ^0.2.1
   ```

3. Use [tizen_interop](https://github.com/flutter-tizen/tizen_interop)'s `connection_get_mac_address` function to retrieve the ethernet adapter's MAC address as follows. (Note: You can use the `connection_get_type` function if you want to get the currently active network adapter's information.)

   ```dart
   import 'dart:ffi';
   import 'package:ffi/ffi.dart';
   import 'package:tizen_interop/4.0/tizen.dart';

   String? getMacAddress() {
     return using((Arena arena) {
       final Pointer<connection_h> pConnection = arena();
       if (tizen.connection_create(pConnection) != 0) {
         return null;
       }
       final connection_h connection = pConnection.value;
  
       try {
         final Pointer<Pointer<Char>> pAddress = arena();
         const int type = connection_type_e.CONNECTION_TYPE_ETHERNET;
         if (tizen.connection_get_mac_address(connection, type, pAddress) != 0) {
           return null;
         }
         arena.using(pAddress.value, calloc.free);
  
         return pAddress.value.toDartString();
       } finally {
         tizen.connection_destroy(connection);
       }
     });
   }

   print('Current MAC address: ${getMacAddress()}');
   ```
   ```text
   flutter: Current MAC address: 52:54:00:12:34:56
   ```
