### ISSUE TITLE
[video_player] seekto error

### ISSUE THREAD

**Issue by phyochan** [flutter-tizen/plugins#514]
i already try with emulator and real device (Samsung Smart Monitor M8) 

i can not seek video  

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(player_set_play_position failed, Seek operation failure, null, null)

**Comment by swift-kim** [comment]
Hmm. In my case the seek operation crashes the app with a SIGSEGV. Let me take a look. Which version of video_player_tizen are you using?

**Comment by phyochan** [comment]
video_player_tizen: ^2.4.3 bro

**Comment by swift-kim** [comment]
@phyochan Could you elaborate on how to reproduce the issue? Did you just use the example app in the package?

**Comment by phyochan** [comment]
Yes. i just use the example app in the package.

Video player version is 

video_player: ^2.4.2
video_player_tizen: ^2.4.3

**Comment by swift-kim** [comment]
@phyochan Has your issue been resolved? Please also try video_player_tizen 2.4.4 which will be released shortly in this week although I don't think it will fix this specific issue ("Seek operation failure").

**Comment by phyochan** [comment]
I download your latest video player plugin and then added in local library for testing

It work. Video player can seek and no app crash

Thanks
