### ISSUE TITLE
What's the proper way to exit a Tizen app ?

### ISSUE THREAD

**Issue by nassimus26** [flutter-tizen/plugins#532]
My app has been reject with this reason : 
```
Rejected Model Groups
21TV_BASIC1,21TV_PREMIUM1,21TV_PREMIUM2,21TV_STANDARD1,22TV_BASIC1,22TV_PREMIUM1,22TV_PREMIUM2,22TV_PREMIUM3,22TV_PREMIUM4,22TV_PREMIUM5,22TV_STANDARD1
Reason
CRITICAL: The exit button don't work. Please fix this.

```
here the code of the exit button : 
```
void exitApp() {
  if (Platform.isWindows)
    exit(0);
  else {
    SystemNavigator.pop();
  }
}

```

- Is there a plugin which offer a proper way to kill the app ?

**Comment by nassimus26** [comment]
I just found this one https://pub.dev/packages/flutter_exit_app

**Comment by nassimus26** [comment]
My exit button seems working on the emulator (`SystemNavigator.pop()` is doing the job), they are probably talking about the exit button of the remote control.

**Comment by nassimus26** [comment]
Even the back button of the remote control is closing the app, so I don't understand why this rejection ?!

**Comment by nassimus26** [comment]
I think I found the issue, please close this, if you have no comment about it

**Comment by swift-kim** [comment]
The exit key on the remote control should close the app if the key event is not explicitly [handled](https://api.flutter.dev/flutter/widgets/KeyEventResult.html#handled) in your code or `SystemNavigator.pop()` is called.

> I think I found the issue,

Oh, what was your finding?

**Comment by nassimus26** [comment]
In my code, I was adding a counter, which ensure that the user didn't press the Back button by error, 
The first press was ignored, because even myself I often press the back button by error, when for example I try to pause the video.

Now I removed the counter I hope they will validate it.

**Comment by swift-kim** [comment]
Since they specifically mentioned that the problem was with the the "exit" button, the issue should have nothing to do with the "back" button. If you figure out how to reproduce the issue, please let us know.

**Comment by nassimus26** [comment]
The Exit button inside the app was working without any counter, if they are talking about it, I don’t know what to change. 

Anyway I pushed a new version, we will see if they still complaining about it

**Comment by nassimus26** [comment]
Hi @swift-kim  please re-open this one, they keep rejecting my app for the 4 th time with the same reason : 

REJECTION REASON :

"The exit button don't work" Dear Developer, Hope everything is well! According to Samsung's return policy in regards to terminating applications, when pressing the "Return" key an exit pop-up should be displayed and the app should be terminated upon the user pressing "Yes", you can find more information regarding this policy here: https://developer.samsung.com/smarttv/develop/guides/fundamentals/terminating-applications.html If your application is already implementing the policy, you may mark the defect as fixed and indicate it as “expected behavior”, this should close the problem in the next certification process. If you have further questions or need additional details, please feel free to let us know by opening a new round of 1:1 Q&A. Best regards, Samsung Team.

Here the link to my app, I tested on the Emulator, the Exit button is working fine after showing the confirmation dialog with YES or No 

https://raw.githubusercontent.com/nassimus26/naviptv/main/apks/com.agiprod.naviptv.tpk

Could someone try my app and tell me what's truly wrong with it ?

Thank you in advance.
