### ISSUE TITLE
video player in tizen tv

### ISSUE THREAD

**Issue by goliveok** [flutter-tizen/plugins#533]
hi all

i have problem in video_player tizen tv

There is sound and the video image is white, the video does not appear

I need your help playing a video image.

my system linux ubuntu
Tizen T-samsung-7.0-x86  virtual in ubuntu

Using hardware rendering with device Tizen T-samsung-7.0-x86. If you notice graphics
artifacts, consider enabling software rendering with "--enable-software-rendering".
Launching tizen/flutter/generated_main.dart on Tizen T-samsung-7.0-x86 in debug
mode...
The TPK was signed with the default certificate. You can create one using Certificate
Manager.
https://github.com/flutter-tizen/flutter-tizen/blob/master/doc/install-tizen-sdk.md#c
reate-a-tizen-certificate
Building a Tizen application in debug mode...                      35.0s
✓ Built build/tizen/tpk/com.example.tizen-1.0.0.tpk (30.2MB).
Installing build/tizen/tpk/com.example.tizen-1.0.0.tpk...           5.4s
[E] [WARN][(tid:4477)(_wl_egl_tizen_get_tizen_private)] Should create tpl_surface with this wl_egl_window first.
[WARN][(tid:4477)(_wl_egl_tizen_get_tizen_private)] All wl_egl_window_tizen APIs will be ignored.
Syncing files to device Tizen T-samsung-7.0-x86...                 146ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

💪 Running with sound null safety 💪

An Observatory debugger and profiler on Tizen T-samsung-7.0-x86 is available at:
http://127.0.0.1:41967/frvH50ibfPY=/
The Flutter DevTools debugger and profiler on Tizen T-samsung-7.0-x86 is available
at: http://127.0.0.1:9100?uri=http://127.0.0.1:41967/frvH50ibfPY=/

**Comment by xuelian-bai** [comment]
hi, TV emulator is not supported for video_player plugin,  you may get more info about device limitation here https://github.com/flutter-tizen/plugins, you can use TV device to run video_player plugin.

**Comment by goliveok** [comment]
Can you help me run url video in TV emulator or other player  for my application because I do not have a tizen TV real
