### ISSUE TITLE
[audioplayers] Audio HLS not supported

### ISSUE THREAD

**Issue by dan-live365** [flutter-tizen/plugins#536]
Hello!
I'm using audioplayers_tizen to stream audio to a Tizen TV app.
In order to achieve that I'm using a
`AudioPlayer _tizenPlayer = AudioPlayer();
await _tizenPlayer!.play(UrlSource(url));`
Everytime I try to play from a HLS stream I get:

> [E] [ERROR:flutter/runtime/dart_vm_initializer.cc(41)]
Unhandled Exception: Not supported format
#0      MethodChannelAudioplayersPlatform._doHandlePlatformCall (package:audioplayers_platform_interface/method_channel_audioplayers_platform.dart:174:9)
#1      MethodChannelAudioplayersPlatform.platformCallHandler (package:audioplayers_platform_interface/method_channel_audioplayers_platform.dart:147:7)
#2      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:536:55)
#3      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:529:34)
#4      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:387:35)
#5      _invoke2 (dart:ui/hooks.dart:186:13)
#6      _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
#7      _Channel.push (dart:ui/channel_buffers.dart:132:31)
#8      ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
#9      PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:599:22)
#10     _dispatchPlatformMessage (dart:ui/hooks.dart:89:31)

Before that I've used ICY stream that was running fine.

Examples of the streams are:
- HLS: https://streaming.live365.com/a30478/playlist.m3u8
- ICY: https://streaming.live365.com/a30478

I've been looking through the Tizen docs if there are any HLS limitations, but couldn't find anything.
My question is: does this plugin support audio HLS streaming?

**Comment by wanchao-xu** [comment]
audioplayers plugin support HLS audio, This error is caused by timeout when request https://streaming.live365.com/a30478/playlist.m3u8.
The audioplayers made a http request to play HLS audio, but if it doesn't get response in 10 seconds, audioplayers of tizen will retry again. After 3 times, audioplayers will abort the operation.
I tried other hls audio, audioplayers plugin of tizen can play it successfully.

**Comment by dan-live365** [comment]
Hey, thank you very much for the reply!
I don't know why the timeout occurs at the moment, as there is no geoblocking added to the stream.
Could you provide more info or documentation on which HLS formats that are currently supported on Tizen?

**Comment by xuelian-bai** [comment]
You can find more details here https://developer.samsung.com/smarttv/develop/specifications/general-specifications.html
