### ISSUE TITLE
Please support agora_rtc_engine plugin

### ISSUE THREAD

**Issue by bauloc** [flutter-tizen/plugins#551]
Pleae support **agora_rtc_engine** plugin
https://pub.dev/packages/agora_rtc_engine/versions/5.3.1

Thank you!

**Comment by xuelian-bai** [comment]
hi, agora plugin is the wrapper of Agora RTC SDK, but now Agora is not installed on Tizen platform, so you can only run it on Android phone.
As an alternative, we have this plugin https://github.com/flutter-tizen/plugins/tree/master/packages/flutter_webrtc

**Comment by bauloc** [comment]
Thank you
