### ISSUE TITLE
Please consider coast_audio support.

### ISSUE THREAD

**Issue by hl4hck** [flutter-tizen/plugins#558]
Hi,

Please consider coast_audio support.
https://pub.dev/packages/coast_audio

It was recently added to pub.dev.
I'm working on a solution that modifies audio buffers in real time. 
I want to make a tizen support package myself, but I'm new to Flutter, so I'm registering a request issue.

Please consider coast_audio support.

**Comment by swift-kim** [comment]
Hi. The library is written in pure Dart and doesn't seem to have any platform dependency. Didn't the package work on Tizen?

**Comment by hl4hck** [comment]
Hi,

I mistakenly believed that porting was necessary to use plugins in Tizen. I tested coast_audio on Tizen and it works well.

However, the plugin I will actually be using is "coast_audio_miniaudio".
coast_audio_miniaudio is an extension package for coast_audio using miniaudio.
https://pub.dev/packages/coast_audio_miniaudio

By the way, coast_audio_miniaudio does not yet support Linux. (There is no mabridge library for linux yet.)
So, after testing coast_audio_miniaudio to work on Linux, I'm going to test it on Tizen.

I'll let you know if there are any issues.

Thank you!

**Comment by swift-kim** [comment]
It seems technically possible to build the libmabridge for Tizen armel from source and link it with coast_audio_miniaudio, but you will need enough knowledge about all the relevant technologies. Adding Linux support is a good starting point if you're familiar with Linux.

**Comment by hl4hck** [comment]
@swift-kim 
Thank you for your advice.
I need to study more, but it looks good to build directly from the source code for Tizen armel.
Thank you!
