### ISSUE TITLE
[video_player_videohole] Missing dart_api_dl.h

### ISSUE THREAD

**Issue by mhoeckner** [flutter-tizen/plugins#566]
Hi

I do think there is a file missing in the repo -> tizen/src/dart_api_dl.h

_In file included from src/video_player.cc:14:
src/pending_call.h:8:10: fatal error: 'dart_api_dl.h' file not found
#include <dart_api_dl.h>_

Also in line 411 drm_license_helper.cc log info needs adaptations - missing data arguments ->

_LOG_INFO("[DrmLicenseHelper] %s:%d curl works canceled.");_

thank you in advance
regards
Markus

**Comment by swift-kim** [comment]
It looks like you're using the latest video_player_videohole plugin which hasn't been released yet.

We recently added a patch (https://github.com/flutter-tizen/flutter-tizen/pull/488) to the flutter-tizen tool, so you need to update it to the latest to suppress the error.

**Comment by mhoeckner** [comment]
Ah - nice - after upgrade it works - thx!
