### ISSUE TITLE
Support WorkManager for Tizen

### ISSUE THREAD

**Issue by kazakan** [flutter-tizen/plugins#595]
In Linux, `System Daemon` can run jobs in background periodically. In android, `WorkManager` do such a thing.

They not only support launching jobs periodically in background but also support persistent launching after system reboot. And jobs can be triggered or not depending on network state or battery level.

There's already flutter package that wraps `WorkManager`. [link](https://pub.dev/packages/workmanager)

I think this could be implemented using tizen job scheduling api. [link](https://github.com/Samsung/tizen-docs/blob/master/docs/application/native/guides/app-management/job-scheduler.md)

Implementing for tizen would be nice for future application development.

Other refs.
- [Tizen job scheduling api](https://docs.tizen.org/application/native/api/mobile/5.0/group__CAPI__JOB__SCHEDULER__MODULE.html)
- [Andoid workmanager](https://developer.android.com/topic/libraries/architecture/workmanager/basics?hl=ko)

**Comment by JSUYA** [comment]
Hi @kazakan Thank you for suggestion.
Can you explain more.. a example(?) that Tizen's job scheduler is used?
And in Flutter, can you explain also how to use work manager in real case?

If flutter-tizen supports the work-manager plugin, in what cases can we use it?

**Comment by kazakan** [comment]
There are jobs executed periodically and can be finished in short time in background like 
  - "Send logs to server for every 2 hours"
  - "Sync data with firebase every 4 hours"
  - "Check for update every 24 hours".

I haven't used Tizen's job scheduler api, but I used android's WorkManager for those purposes. Also, they were not time critical like Timer. Jobs can be executed almost every 2 hours but **not exactly** 2 hours. 

Difference between using Dart `isolate` and `WorkManager` is isolate cannot be executed automatically after system crash or device reboot, but WorkManager (or Job Scheduler in tizen) can.

We can use WorkManager in flutter by making one callback function (dart entry) to execute jobs and register job with some policies in other places.

```dart
// From https://pub.dev/packages/workmanager
@pragma('vm:entry-point') 
void callbackDispatcher() {
  Workmanager().executeTask((task, inputData) {
    print("Native called background task: $task"); //simpleTask will be emitted here.
    return Future.value(true);
  });

void main() {
  Workmanager().initialize(
    callbackDispatcher, // The top level function, aka callbackDispatcher
    isInDebugMode: true 
  );
  Workmanager().registerOneOffTask("task-identifier", "simpleTask"); // register job
  runApp(MyApp());
  }
}
```

If this flutter-tizen supports this plugin, implementing jobs that runs periodically and can be finished in short time in background in flutter be easier than before I think.

**Comment by JSUYA** [comment]
This job is no longer progressing and there are no plans to progress it again until now. If there is a requirement, this job can be resumed.

**Comment by JSUYA** [comment]
https://github.com/flutter-tizen/plugins/pull/608
