### ISSUE TITLE
dart analyze error (dart 3.1.0)

### ISSUE THREAD

**Issue by JSUYA** [flutter-tizen/plugins#609]
The version of flutter has been upgraded to 3.13.
https://medium.com/flutter/whats-new-in-flutter-3-13-479d9b11df4d
and dart has been upgraded to version 3.1.
https://medium.com/dartlang/dart-3-1-a-retrospective-on-functional-style-programming-in-dart-3-a1f4b3a7cdda

This caused an error in dart anlyze.
https://github.com/flutter-tizen/plugins/actions/runs/5886027065/job/15963281387#step:4:1188

This page tracks issues with flutter and dart upgrades.

- [ ] audioplayers (https://pub.dev/packages/audioplayers/changelog)
- [ ] flutter_secure_storage
- [ ] sqflite

**Comment by swift-kim** [comment]
Is there anyone working on this? An immediate action should be taken.

**Comment by Swanseo0** [comment]
@swift-kim I am responding to this issue.
Currently, audioplayers are being updated.
