### ISSUE TITLE
[video_player_videohole] Detailed errors

### ISSUE THREAD

**Issue by IhabMks** [flutter-tizen/plugins#616]
Is there a way to get a detailed error like a stack or something, because currently, i only get a small message saying the video format not supported and that's it, and which not very helpful to get exactly why the video couldn't be played.

**Comment by xuelian-bai** [comment]
hmm. Player can only return such errors, player call multiple platform libs to encode/decode/..., it can't get detailed error from other libs.
For more details, we need to check detailed logs from other platform libs, these logs couldn't be seen on TV with release image. If you got error, please file a issue, provide your stream or tpk of app, we will check platform logs.
