### ISSUE TITLE
Firebase core - how to use it

### ISSUE THREAD

**Issue by Stuggy** [flutter-tizen/plugins#618]
Sorry for not being able to work it out but how do you add data to firebase?  I had it working a while ago using another package [https://pub.dev/packages/firebase_auth_rest](url) but decided to switch to the flutter-tizen package.

The example show how to initialize the FirebaseApp but I can't work out how to save any data for example.

The flutter-tizen implementation is based on [https://github.com/FirebaseExtended/flutterfire_desktop/tree/main](url).  Do I have to add other packages?

A very basic example would be appreciated.

**Comment by swift-kim** [comment]
AFAIK, firebase_core_tizen is a base package for supporting other FlutterFire plugins. [firebase_auth_tizen](https://github.com/flutter-tizen/plugins/pull/511) and [firebase_functions_tizen](https://github.com/flutter-tizen/plugins/pull/498) are currently under review, but there's currently no package for Tizen that supports "saving data" to the cloud (because [flutterfire_desktop](https://github.com/FirebaseExtended/flutterfire_desktop/tree/main/packages) doesn't support it either).

@daeyeon @hs0225 Do you have any comments?

**Comment by Stuggy** [comment]
Ok thanks for the reply but I have been saving to the cloud using I think the package I mentioned above.  I think it wasn't specifically Tizen but was Dart and worked.  Now after coming back to my app I am getting errors that probably are not specifically TIzen but related to updated packages I assume.  I'll copy and paste the errors.

**Comment by Stuggy** [comment]
`flutter-tizen run
url_launcher_tizen is available on pub.dev. Did you forget to add to pubspec.yaml?
Launching tizen\flutter\generated_main.dart on Tizen SM-R820 in debug mode...
lib/status.dart:18:27: Error: Couldn't find constructor 'Jiffy'.
    var timeOfFirstShot = Jiffy(DateTime.now(), "EEE, dd MMM yyyy hh:mm a zzz");  // always set it to now and then it
    gets reset if the round has started
                          ^^^^^
lib/status.dart:20:25: Error: Couldn't find constructor 'Jiffy'.
      timeOfFirstShot = Jiffy(dxCourses.roundstarttime.value, "EEE, dd MMM yyyy hh:mm a zzz");
                        ^^^^^
lib/status.dart:22:23: Error: Couldn't find constructor 'Jiffy'.
    var currentTime = Jiffy(DateTime.now());
                      ^^^^^
lib/status.dart:36:23: Error: Couldn't find constructor 'Jiffy'.
    var timeElapsed = Jiffy('${hour.toInt()}:${minute.toInt()}', 'hh:mm');
                      ^^^^^
/C:/Users/Stu/AppData/Local/Pub/Cache/hosted/pub.dev/firebase_database_rest-1.0.3/lib/src/rest/models/stream_event.freezed.dart:25:13: Error: Method not found: 'FallThroughError'.
      throw FallThroughError();
            ^^^^^^^^^^^^^^^^`

**Comment by Stuggy** [comment]
I did a temporary fix by replaced FallThroughError with UnspecifiedError.

On another front I can't get the Samsung certificate manager to create a Samsung certificate.  I just get  a blank screen on the login.  Onward I guess...

**Comment by swift-kim** [comment]
@Stuggy Tizen Certificate Manager is trash and often broken. If you're on Windows, please refer to the following link and try another machine (macOS or Linux) if available (or just wait until the issue gets fixed).

https://forum.developer.samsung.com/t/trying-to-log-in-to-get-a-distribute-certificate

Also as far as I heard our member @daeyeon is working on a Tizen version of the `firebase_database` plugin. I hope it will be available soon.

**Comment by Stuggy** [comment]
Thanks for the idea.  I had considered trying something like that.  I have Ubuntu on one device that I can try.
