### ISSUE TITLE
Ongoing Activity

### ISSUE THREAD

**Issue by masus04** [flutter-tizen/plugins#645]
Is there a way to create ongoing activities using these packages?

Google Play Store recently added the implementation of Ongoing Activities as required features for wearable apps where applicable, such as for any kind of timer.

**Comment by swift-kim** [comment]
The packages in this repo is not for Wear OS. Are you sure you're developing a Tizen application?

**Comment by masus04** [comment]
Well, I have successfully used some of these packages in my wearOS apps, such as wearable_rotary, so I think they are at least somewhat similar.

Is there any reason they should not be?

Also, am I correct in assuming Tizen watches also support ongoing activities?

**Comment by DanielMartini** [comment]
Hey @masus04, I just managed to implement ongoing activities with https://github.com/Rexios80/wear_ongoing_activity package.

If you are planning to release the app on the play store, you will have to downgrade the targetSdkVersion to 33, as the package is aiming to version 34 and it is still not supported on the store, take a look to my fork if you need

**Comment by swift-kim** [comment]
> I think they are at least somewhat similar.

Tizen and Wear OS are completely different operating systems. Only the wearable_rotary package in this repo supports both. The rest are Tizen only.

> Also, am I correct in assuming Tizen watches also support ongoing activities?

No, as far as I know. The concept (Ongoing Activity) is new in Wear OS. @DanielMartini Thank you for the suggestion and the tip!

**Comment by masus04** [comment]
Great, thank you both for the clarification and additional resources :+1:
