### ISSUE TITLE
Not supporting low latency mode (HLS)

### ISSUE THREAD

**Issue by tzutoo** [flutter-tizen/plugins#648]
https://pub.dev/packages/video_player_tizen
'https://stream.mux.com/v69RSHhFelSm4701snP22dYz2jICy4E4FUyk02rW4gxRM.m3u8'

[E] [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(Pause, Player pause failed, null, null)
#0      VideoPlayerVideoholeApi.pause (package:video_player_videohole/src/messages.g.dart:759)
<asynchronous suspension>
#1      VideoPlayerController._applyPlayPause (package:video_player_videohole/video_player.dart:584)
<asynchronous suspension>
[E] [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(SetPlaybackSpeed, Player set playback speed failed, null, null)
#0      VideoPlayerVideoholeApi.setPlaybackSpeed (package:video_player_videohole/src/messages.g.dart:550)
<asynchronous suspension>
#1      VideoPlayerController._applyPlaybackSpeed (package:video_player_videohole/video_player.dart:607)
<asynchronous suspension>
#2      VideoPlayerController._applyPlayPause (package:video_player_videohole/video_player.dart:581)
<asynchronous suspension>
#3      VideoPlayerController.play (package:video_player_videohole/video_player.dart:508)
<asynchronous suspension>

**Comment by xuelian-bai** [comment]
Low latency HLS is not supported for now, we will check this crash soon.(we got network issue this week, so can't reproduce this crash)

**Comment by hyue7** [comment]
@tzutoo  Hi, I really recommend you use [video_player_avplay](https://github.com/flutter-tizen/plugins/tree/master/packages/video_player_avplay), the feature is available using avplay.
