### ISSUE TITLE
[video_player_avplay] pausing video will throw an error and can not resume play in some situtaion

### ISSUE THREAD

**Issue by elethiame** [flutter-tizen/plugins#657]
@xiaowei-guan 
When I pause the video, an error is thrown:
[E] [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(Pause, Player pause failed, null, null)
#0 VideoPlayerAvplayApi.pause (package:video_player_avplay/src/messages.g.dart:803:7)
<asynchronous suspension>
#1 VideoPlayerController._applyPlayPause (package:video_player_avplay/video_player.dart:615:7)
<asynchronous suspension>
#2 VideoPlayerController.pause (package:video_player_avplay/video_player.dart:543:5)
<asynchronous suspension>

Additionally, if I play video in a different app, like Bilibili, and then resume my app, the AVPlay will not replay the video.

**Comment by xiaowei-guan** [comment]
@elethiame 
Can you describe in detail the steps to reproduce?

**Comment by elethiame** [comment]
`class RunningPage extends StatefulWidget {
  const RunningPage({Key? key}) : super(key: key);

  @override
  _RunningPageState createState() => _RunningPageState();
}

class _RunningPageState extends State<RunningPage> {
  late VideoPlayerController _controller;
  late final AppLifecycleListener _appLifecycleListener;
  @override
  void initState() {
    super.initState();
    _controller = VideoPlayerController.asset('assets/videos/config_video.mp4')
      ..initialize().then((_) {
        _controller.setLooping(true);
        _controller.play();
      });

    _appLifecycleListener = AppLifecycleListener(
      onStateChange: (state) async {
        if (state == AppLifecycleState.resumed) {
          UILogger.info('app resumed, play video');
          _controller.play();
        } else if (state == AppLifecycleState.paused) {
          UILogger.info('app paused, pause video');
          _controller.pause();
        }
      },
    );
  }

  @override
  void dispose() {
    _controller.dispose();
    _appLifecycleListener.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.black,
      body: Stack(
        fit: StackFit.expand,
        alignment: Alignment.center,
        children: [
          AspectRatio(
            aspectRatio: _controller.value.aspectRatio,
            child: VideoPlayer(_controller),
          ),
          Focus(
            autofocus: true,
            onKey: (node, event) {
              if (event is RawKeyDownEvent) {}
              if (event.isConfirmKeyPressed() || event.isEscapeKeyPressed()) {
                _stop(context);
                return KeyEventResult.handled;
              }
              return KeyEventResult.ignored;
            },
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              mainAxisSize: MainAxisSize.min,
              children: [
                Text(
                  context.localizations.runningPageSubtitle,
                  style: TextStyle(
                    fontSize: 24.px,
                    fontWeight: FontWeight.w500,
                    color: Color(0x99FFFFFF),
                  ),
                ),
                SizedBox(
                  height: 20.px,
                ),
                _buildRichText(),
              ],
            ),
          ),
          _buildCapturePosition(),
        ],
      ),
    );
  }
}`

When this page is loaded, an error is thrown, but everything else seems alright:

`[E] [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(Pause, Player pause failed, null, null)
#0 VideoPlayerAvplayApi.pause (package:video_player_avplay/src/messages.g.dart:803:7)

https://github.com/flutter-tizen/plugins/pull/1 VideoPlayerController._applyPlayPause (package:video_player_avplay/video_player.dart:615:7)

https://github.com/flutter-tizen/plugins/pull/2 VideoPlayerController.pause (package:video_player_avplay/video_player.dart:543:5)`

Then, I return to the TV home screen and open Bilibili to play a video. After that, when I go back to my app, the video widget appears black.

I am using this package on Samsung TV Q60C/Q70C for China.

**Comment by xuelian-bai** [comment]
Hi, in China current TV products are different from global TV, both android app and tizen app can run on Chinese products,  if you develop tizen app, you need to send request to us for app entry(your app will be shown in "我的应用") when release.
