### ISSUE TITLE
[wearable_rotary] First RotaryController of NavigationStack never dismissed

### ISSUE THREAD

**Issue by MichaelLucca** [flutter-tizen/plugins#673]
**Description:**
In a WearOS app, I'm using the RotaryController(). When I navigate from the Home to another non-scrollable page, in the logs I see that the RotaryController defined in Home is still being triggered

**Expected Behavior:**
The RotaryController of the current page should be triggered, not the one from which I am navigating from

**Comment by swift-kim** [comment]
Not very elegant, but the following is the only solution I found. You need to modify the `RotaryScrollController` class itself.
```patch
--- a/packages/wearable_rotary/lib/src/rotary_scroll_controller.dart
+++ b/packages/wearable_rotary/lib/src/rotary_scroll_controller.dart
@@ -18,6 +18,13 @@ class RotaryScrollController extends ScrollController {
   final double maxIncrement;
 
   void _onRotaryEvent(RotaryEvent event) {
+    if (position.context.notificationContext != null) {
+      final route = ModalRoute.of(position.context.notificationContext!);
+      if (route != null && !route.isCurrent) {
+        return;
+      }
+    }
+
     final double increment = min(event.magnitude ?? maxIncrement, maxIncrement);
 
     final double newOffset;
```
I'm personally not familiar with writing Flutter app code, so there may be better options.

**Comment by MichaelLucca** [comment]
Thanks a lot @swift-kim 🤙🏻
