### ISSUE TITLE
[video_player_avplay] Unable to build for 8.0 Tizen Version

### ISSUE THREAD

**Issue by AMarozzi** [flutter-tizen/plugins#680]
Hello Tizen Team,

we have tried to support the 8.0 version of the Tizen Os for 2024 Tv lines but when it's come to build and run the app on the emulator a build error happens. 

Here the log [build_error.txt](https://github.com/flutter-tizen/plugins/files/15185089/build_error.txt)

How can we fix? Futhermore the error is not happening when build on real 2023 Tv lines or old version on remote emulator.

**Comment by xiaowei-guan** [comment]
> video_player_avplay does not support 8.0 yet. @xiaowei-guan Could you please support 8.0 plusplayer?

I am doing this part of the work. Checking a issue with the security team.

**Comment by xiaowei-guan** [comment]
> Hello Tizen Team,
> 
> we have tried to support the 8.0 version of the Tizen Os for 2024 Tv lines but when it's come to build and run the app on the emulator a build error happens.
> 
> Here the log [build_error.txt](https://github.com/flutter-tizen/plugins/files/15185089/build_error.txt)
> 
> How can we fix? Futhermore the error is not happening when build on real 2023 Tv lines or old version on remote emulator.

```
amarozzi@amarozziMB16 technogym-training-flutter % flutter-tizen run -v
[ +139 ms] executing: sysctl hw.optional.arm64
[  +17 ms] Exit code 1 from: sysctl hw.optional.arm64
[        ] sysctl: unknown oid 'hw.optional.arm64'
```
Hello, Do you build app for ARM64?

**Comment by xiaowei-guan** [comment]
> Do you build app for ARM64?

video_player_avplay doesn't support TV emulator now.

**Comment by AMarozzi** [comment]
> > Do you build app for ARM64?
> 
> video_player_avplay doesn't support TV emulator now.

ok, but we have some defects reported by the TV Seller QA team, specifically on the 2024 TV lines. How can we fix and test these issues without the possibility to use emulator?

**Comment by swift-kim** [comment]
@AMarozzi The problem is that the libraries video_player_avplay depends on are not available for the x86 architecture (emulator). The libraries are only available for real devices (arm). You should use physical TV devices to build and test your app.

**Comment by xuelian-bai** [comment]
@AMarozzi you may try on remote test lab https://developer.samsung.com/remotetestlab/devices/117/tv
and is it possible to reproduce these issues on tizen7.0 tv?

**Comment by xiaowei-guan** [comment]
#682

**Comment by xiaowei-guan** [comment]
@AMarozzi We have supported Tizen 8.0 on TV devices, please apply latest version of plugin.

**Comment by AMarozzi** [comment]
@xiaowei-guan thank for the feedback. I have just update the plugin and release a new version. I will update you with the result of the Tv Seller Office.

**Comment by rinsarmu** [comment]
I tried to use video_player_avplay package. but the following below error is found.
[builderror.txt](https://github.com/user-attachments/files/17026951/builderror.txt)
