### ISSUE TITLE
video_player_avplay crash

### ISSUE THREAD

**Issue by AMarozzi** [flutter-tizen/plugins#701]
Hello,

Sometimes when i try to play an mp4 file the video_player_avplay crash.

Here the log:

> [E] [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
#0      VideoPlayerController.initialize.errorListener (package:video_player_avplay/video_player.dart:480:51)
#1      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#2      _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:386:15)
#3      _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:402:7)
#4      _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:306:7)
#5      _ForwardingStreamSubscription._addError (dart:async/stream_pipe.dart:128:11)
#6      _ForwardingStream._handleError (dart:async/stream_pipe.dart:95:10)
#7      _ForwardingStreamSubscription._handleError (dart:async/stream_pipe.dart:157:13)
#8      _RootZone.runBinaryGuarded (dart:async/zone.dart:1606:10)
#9      _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:384:15)
#10     _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:402:7)
#11     _DelayedError.perform (dart:async/stream_impl.dart:552:14)
#12     _PendingEvents.handleNext (dart:async/stream_impl.dart:646:11)
#13     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:617:7)
#14     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#15     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
[E] [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
#0      VideoPlayerController.initialize.errorListener (package:video_player_avplay/video_player.dart:480:51)
#1      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#2      _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:386:15)
#3      _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:402:7)
#4      _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:306:7)
#5      _ForwardingStreamSubscription._addError (dart:async/stream_pipe.dart:128:11)
#6      _ForwardingStream._handleError (dart:async/stream_pipe.dart:95:10)
#7      _ForwardingStreamSubscription._handleError (dart:async/stream_pipe.dart:157:13)
#8      _RootZone.runBinaryGuarded (dart:async/zone.dart:1606:10)
#9      _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:384:15)
#10     _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:402:7)
#11     _DelayedError.perform (dart:async/stream_impl.dart:552:14)
#12     _PendingEvents.handleNext (dart:async/stream_impl.dart:646:11)
#13     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:617:7)
#14     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#15     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)

**Comment by swift-kim** [comment]
@JSUYA @xiaowei-guan Similar issue: https://github.com/flutter-tizen/plugins/issues/261

Both `media_player.cc` and `plus_player.cc` seem to have the issue (null pointer possibly being passed to `SendError`).

A possible fix (applied in `video_player`): https://github.com/flutter-tizen/plugins/blob/9bd3d3e14304a0ac184e68c300b112fbeb48df29/packages/video_player/tizen/src/video_player.cc#L540-L541

Another possible workaround is to edit `video_player.dart` directly.

**Comment by xiaowei-guan** [comment]
> @JSUYA @xiaowei-guan Similar issue: #261
> 
> Both `media_player.cc` and `plus_player.cc` seem to have the issue (null pointer possibly being passed to `SendError`).
> 
> A possible fix (applied in `video_player`):
> 
> https://github.com/flutter-tizen/plugins/blob/9bd3d3e14304a0ac184e68c300b112fbeb48df29/packages/video_player/tizen/src/video_player.cc#L540-L541
> 
> Another possible workaround is to edit `video_player.dart` directly.

Ok, I will fix this issue.
