### ISSUE TITLE
video_player_avplay issues  after the last seek performed 

### ISSUE THREAD

**Issue by AMarozzi** [flutter-tizen/plugins#712]
Hello Team,

Samsung Quality Team reported this error. If the user seek to the end of the video the avplay throw an error and start not responding. We cannot exit or moving to the next video.

`From the shared log file, after the last seek performed there is data played for ~5 sec

so need to check app side why progress bar is not moved on UI

01-01 01:37:55.297+0100 I/PLUSPLAYER(P10317, T11313): defaultplayer.cpp: OnSeekDone(3218) > ENTER

01-01 01:37:55.368+0100 W/GST_LOG (P10317, T11313): gstwaylandsink.c: gst_wayland_sink_send_buf(7190) > [0x9d43c328]seq_p_s[11],render_cost[18],pts[986440],render_interval[52]/ms

01-01 01:38:00.229+0100 W/GST_LOG (P10317, T11313): gstwaylandsink.c: gst_wayland_sink_send_buf(7190) > [0x9d43c328]seq_p_s[11],render_cost[0],pts[991320],render_interval[79]/ms`

Can you help us?

**Comment by xiaowei-guan** [comment]
I have checked this issue, your TPK file which build for Tizen 6.0, can't run it on Tizen 8.0 

If your app for tizen 6.0, 2021 tv model:
```
<manifest package="xxx" version="1.0.0" api-version="6.0">
```
if your app for tizen 6.5, 2022 tv model :
```
<manifest package="xxx" version="1.0.0" api-version="6.5">
```
if your app for tizen 7.0, 2023 tv model :
```
<manifest package="xxx" version="1.0.0" api-version="7.0">
```
if your app for tizen 8.0, 2024 tv model :
```
<manifest package="xxx" version="1.0.0" api-version="8.0">
```

**Comment by xiaowei-guan** [comment]
This is app issue

**Comment by AMarozzi** [comment]
> This is app issue

You are right, we have fixed in the app.
