### ISSUE TITLE
[video_player_tizen] Need update to 2.7.0 or later

### ISSUE THREAD

**Issue by JSUYA** [flutter-tizen/plugins#727]
The VideoPlayerController.network API is deprecated.
https://github.com/flutter/packages/blob/main/packages/video_player/video_player/CHANGELOG.md#270
In order to make a smooth transfer to the Tizen platform from original flutter app, we need to support the latest interface.
(This also applies to _avplay and _videohole plugin.)

**Comment by T-h-e-Wizard** [comment]
(Once I've switched to the versions mentioned in the readme of `video_player_tizen` plugin, things got better... but...)

Please note that, having the latest version of `video_player` (2.9.1 as of my recent tests), and then adding `video_player_tizen` dependency caused an error like this in VS Code console (I've entered the worlds of both flutter and Tizen very recently, so... sorry, if this is a newbie oversight)
```flutter pub add video_player_tizen
Because 
	video_player_tizen <2.2.0 
		depends on video_player_platform_interface ^4.1.0 
	and video_player_tizen >=2.2.0 <2.4.0 
		depends on video_player_platform_interface ^4.2.0, 
	video_player_tizen <2.4.0 requires video_player_platform_interface ^4.1.0.

And because 
	video_player_tizen >=2.4.0 
		depends on video_player_platform_interface ^5.1.2 
	and video_player >=2.9.0 
		depends on video_player_platform_interface ^6.2.0, 
	video_player >=2.9.0 is incompatible with video_player_tizen.
So, because my_video_player depends on both video_player ^2.9.1 and video_player_tizen any, version solving failed.
```

**Comment by swift-kim** [comment]
@T-h-e-Wizard Sorry for the inconvenience. The issue will soon be fixed by the linked PR (https://github.com/flutter-tizen/plugins/pull/730) and the updated package (`video_player_tizen` 2.5.0) will be uploaded to pub.dev.
