### ISSUE TITLE
[wakelock_tizen] Frontend package changed

### ISSUE THREAD

**Issue by JSUYA** [flutter-tizen/plugins#728]
wakelock_tizen is the Tizen implementation of [wakelock](https://pub.dev/packages/wakelock).
The wakelock package is no longer maintained.
We need to change it to [wakelock_plus](https://pub.dev/packages/wakelock_plus).

**Comment by swift-kim** [comment]
wakelock_tizen is already wearable-only. We should rather discontinue the package.

**Comment by JSUYA** [comment]
> wakelock_tizen is already wearable-only. We should rather discontinue the package.

Oh you are right. I forgot that this isn't supported on TV.
but... I think we could use screensaver_reset_timeout() to call reset every 30 seconds while WakelockPlus.enable() is called. https://github.com/flutter-tizen/plugins/pull/610
