### ISSUE TITLE
[shared_preferences_tizen] Question: Is the tizen version compatible with 2.3.0+ of the base package? Please upgrade if not

### ISSUE THREAD

**Issue by T-h-e-Wizard** [flutter-tizen/plugins#745]
The subject pretty much says it all. The [base shared_preferences package](https://pub.dev/packages/shared_preferences) is currently at version 2.3.2, and its authors have announced that legacy API will be deprecated, and newer code should be written using `SharedPreferencesAsync` or `SharedPreferencesWithCache` APIs. If the tizen version is not compatible w/ these, it forces users to stick to a "soon to be deprecated" API, which is not preferrable.

I haven't tested the versions yet, and the current tizen version might just work out of the box with 2.3+ base version, but if the developers here can confirm that it's not just "lucky" but indeed working as designed, that would be nice (a change in the readme.md would also help then). If, however, the tizen version is not compatible with 2.3+ of the base, then it's a deterrent to newcomers I think, and should be addressed earlier, rather than later. Thanks!

**Comment by swift-kim** [comment]
@JSUYA Could you please check? I haven't looked into the details but we may need to rewrite the Tizen implementation to support both APIs (the `Async` and `Cache` versions).

**Comment by JSUYA** [comment]
I think.. I should implement the interface of SharedPreferencesAsyncPlatform. I'm preparing a patch. I'll make a PR once it's done.

**Comment by swift-kim** [comment]
Should have been fixed by https://github.com/flutter-tizen/plugins/pull/748. Thank you all.
