### ISSUE TITLE
[webview_flutter_tizen] playing video result in black screen & audio only

### ISSUE THREAD

**Issue by danimnh** [flutter-tizen/plugins#752]
Hi we're prototyping a new app for video playing purposes on Tizen OS

However we came across an issue where our videos are black screens even though the audio works perfectly, we tested youtube on the Samsung TV (Tizen 6.0) main browser and came across the same issue. 

We were wondering if you know what is happening here since using the browser has the same issue and just wondering if this package might offer a solution for this kind of situation?

Reproduce
- Basing off this [Example page](https://pub.dev/packages/webview_flutter_tizen/example)
- use `loadRequest()` to this URL `https://videojs.com/advanced/?video=disneys-oceans` it will show black screen on player section
- youtube also not work even after I delete the testing process on the [Example page](https://pub.dev/packages/webview_flutter_tizen/example)

Requirements
- Real Device is Samsung TV with Tizen OS 6.0
- I have setup the privileges for internet on `tizen-manifest.xml`
- I have `.tizenEnginePolicy` set to true `_controller.tizenEnginePolicy = true;`

**Comment by danimnh** [comment]
https://eu.community.samsung.com/t5/tv/can-t-play-videos-via-web-browser/td-p/928820

maybe related to this case?

**Comment by JSUYA** [comment]
Have you tried this?
When I tested the https://videojs.com/advanced/?video=disneys-oceans example, I confirmed that the video was displayed normally.

```dart
--- a/packages/webview_flutter/example/lib/main.dart
+++ b/packages/webview_flutter/example/lib/main.dart
   @override
   Widget build(BuildContext context) {
     return Scaffold(
-       backgroundColor: Colors.green,
+       backgroundColor: Colors.transparent,
       appBar: AppBar(
         title: const Text('Flutter WebView example'),
```
https://pub.dev/packages/webview_flutter_tizen#note

+) Video playback may not work properly in webview (slow, crashes, etc.). This can be due to a problem with the web engine or device, and the embedded web engine may not provide all functions because it is optimized. Please be aware of this.

**Comment by danimnh** [comment]
Yes we tested on `backgroundColor` set to transparent. 

However we just find out more results

Video.js site I got timeout issue, however I can confirm that Youtube works fine. 
```
[I] flutter: WebView is loading (progress : 10%)
[I] flutter: allowing navigation to https://videojs.com/

[I] flutter: Page resource error:
[I] flutter:   code: 8
[I] flutter:   description: Connection timeout
[I] flutter:   errorType: WebResourceErrorType.timeout
[I] flutter:   isForMainFrame: true
[I] flutter:
[I] flutter: WebView is loading (progress : 100%)
```

Youtube
- My app: Audio only, video is black screen
- Example Page: Works fine
- Browser: Works fine

So i think its more about how I initiialized the webview right? Since the example app is working just fine on youtube.

**Comment by danimnh** [comment]
Hi, just wanted to post an update, somehow I got it working with no crashes. Funny thing is I don't have code changes on my end. 

some checklists are
- TizenEnginePolicy set to true
- transparent backgroundColor on Scaffold
- Tizen Internet privileges

Restarting the TV might help here, but not sure. 

> +) Video playback may not work properly in webview (slow, crashes, etc.). This can be due to a problem with the web engine or device, and the embedded web engine may not provide all functions because it is optimized. Please be aware of this.

might this causes the inconsistency? since sometime it breaks, sometime it works.
