### ISSUE TITLE
Does this package run on Raspberry pi ?

### ISSUE THREAD

**Issue by arun-gautham** [flutter-tizen/plugins#755]
rest of things are working , I get a missing plugin exception...
Note: I only use for data channels not video or audio..

**Comment by JSUYA** [comment]
Hi,
is the OS installed on your Raspberry pi TizenOS?
We need more information. Which plugin is missing? Could you share the error log?

**Comment by arun-gautham** [comment]
I guess it was an issue with flutter_pi, No iam directly building on arm and running.
I Have tested today on Ubuntu on Pi 4, it seems to work, I will try with Raspbian as well and keep you updated.

**Comment by arun-gautham** [comment]
It works perfectly fine on raspbian as well
 thanks
