### ISSUE TITLE
Access webcam/camera from Tizen TV

### ISSUE THREAD

**Issue by mouchegmouradian** [flutter-tizen/plugins#776]
When can we expect [tizen_camera](https://github.com/flutter-tizen/plugins/tree/master/packages/camera) to work on smartTVs ? Or is it planned at all ?

We've build our smartTV app with flutter but are facing more and more issues due to missing features.

**Comment by JSUYA** [comment]
Thank you for your interesting.

Our Camera plugin is an experimental plugin and currently only works on IoT-Headed (RPI board).
https://docs.tizen.org/application/native/api/iot-headed/6.0/group__CAPI__MEDIA__CAMERA__MODULE.html
We currently have no plans to officially support this on TV yet.

We did a quick review of camera API on TV, but found that it requires a partner-level certificate and some APIs do not work properly. Even if we decide to support it, it will take a long time.
Sorry I couldn't be of any help.

**Comment by mouchegmouradian** [comment]
That's unfortunate (we have the partner level certificate). I guess we have to go with web or .net then.
Thank you for your reply.
