### ISSUE TITLE
Recommended video player

### ISSUE THREAD

**Issue by Nygashi** [flutter-tizen/plugins#782]
Hi Flutter-Tizen Team!
Great work on Flutter-tizen, it's working really great so far.

I am currently in the process of creating a cross platform IPTV solution in Flutter. I am now adding Samsung Tizen to my supported platforms.
I have a few questions before i can get started, for which I could not find a proper answer in the supplied documentation:

1. What video player plugin is the recommended one to use for Flutter-tizen? Is this video_player_videohole, video_player_tizen or video_player_avplay? They seem very active and up-to-date, hence my confusion. Performance is key for me, so that has prio.
2. My requirements for the plugin are as follow, does any of the above plugins it support that properly?
- DRM Playready/Widevine
- Adaptive Bitrate
- Livestreams
- Seeking / scrubbing
- I'm creating my own UI, so it needs to be able to handle callbacks+events (started/paused/loading/error etc) , so that I can send that to the Flutter layer and update the UI accordingly.

Thanks in advance, I hope you can help me out!

**Comment by xiaowei-guan** [comment]
@Nygashi  we recommand you use avplay plugin, which is the plugin we mainly support.Avplay is a downloadable plugin, we can fix the player issues quickly. If you want to use this plugin, you need register as a partner.

**Comment by Nygashi** [comment]
@xiaowei-guan Thanks a lot for the quick reply and information! I will continue using that plugin.

**Comment by Nygashi** [comment]
@xiaowei-guan If I run the avplay plugin example project on a physical Samsung TV, the app starts fine and I can play video's properly, so that's great!

The only thing I encounter in the terminal, are the below warnings and errors. Is there any way I can solve those?
I ran the example project with the following command: flutter-tizen run -t lib/main.dart --release

`[E] [WARN][(tid:28773)(_wl_egl_tizen_get_tizen_private)] Should create tpl_surface with this wl_egl_window first.
[WARN][(tid:28773)(_wl_egl_tizen_get_tizen_private)] All wl_egl_window_tizen APIs will be ignored.
[I] [EGL_DBG]: eglGetDisplay:2119, Winsys [tizen] path
[I] [EGL_DBG]: eglInitialize:2263, [Samsung][libmali.so][rel]: Rev: v1.r23p0-01rel0.fae234be103c1a1e2f669a525ae789b2, Winsys: tizen + fbdev, nikem(0), nikel(1), pontusm(0), internal AFBC disable
[E] 
(process:28773): GLib-CRITICAL **: 14:56:36.005: g_path_get_basename: assertion 'file_name != NULL' failed
[I] size of instance = 1240
size of class = 1428
[I] size of basesrc = 448
size of basesrcclass = 404
[I] gst_ffmpegtsfilter_register
[E] 
(<unknown>:28773): GLib-GObject-WARNING **: 14:56:36.822: g_object_set_is_valid_property: object class 'ffdemux_mov_mp4_m4a_3gp_3g2_mj2' has no property named 'input-format'
[E] 
(<unknown>:28773): GStreamer-WARNING **: 14:56:37.021: Trying to set string on structure field 'format', but string is not valid UTF-8. Please file a bug.
[E] 
(<unknown>:28773): GLib-GObject-WARNING **: 14:56:37.022: g_object_set_is_valid_property: object class 'GstMultiQueue' has no property named 'timeout-for-buffering'
[E] 
(<unknown>:28773): GStreamer-CRITICAL **: 14:56:37.028: gst_element_get_static_pad: assertion 'GST_IS_ELEMENT (element)' failed
[E] 
(<unknown>:28773): GStreamer-CRITICAL **: 14:56:37.028: gst_element_get_static_pad: assertion 'GST_IS_ELEMENT (element)' failed
[E] 
(<unknown>:28773): GStreamer-CRITICAL **: 14:56:37.028: gst_pad_link_full: assertion 'GST_IS_PAD (srcpad)' failed
(<unknown>:28773): GStreamer-CRITICAL **: 14:56:37.028: gst_pad_add_probe: assertion 'GST_IS_PAD (pad)' failed
[E] 
(<unknown>:28773): GStreamer-CRITICAL **: 14:56:37.714: gst_structure_new_empty: assertion 'gst_structure_validate_name (name)' failed
[I] ave_ppi_init start
[E] 
(<unknown>:28773): GLib-CRITICAL **: 14:56:37.798: g_str_has_prefix: assertion 'str != NULL' failed
[E] 
(<unknown>:28773): GLib-CRITICAL **: 14:56:37.798: g_str_has_prefix: assertion 'str != NULL' failed
[E] 
(<unknown>:28773): GLib-CRITICAL **: 14:56:37.798: g_str_has_prefix: assertion 'str != NULL' failed
[E] 
(<unknown>:28773): GLib-CRITICAL **: 14:56:37.798: g_str_has_prefix: assertion 'str != NULL' failed
(<unknown>:28773): GLib-CRITICAL **: 14:56:37.798: g_str_has_prefix: assertion 'str != NULL' failed
[E] 
(<unknown>:28773): GLib-CRITICAL **: 14:56:37.799: g_str_has_prefix: assertion 'str != NULL' failed
[E] 
(<unknown>:28773): GLib-CRITICAL **: 14:56:37.801: g_str_has_prefix: assertion 'str != NULL' failed
(<unknown>:28773): GLib-CRITICAL **: 14:56:37.801: g_str_has_prefix: assertion 'str != NULL' failed
(<unknown>:28773): GLib-CRITICAL **: 14:56:37.801: g_str_has_prefix: assertion 'str != NULL' failed
[E] 
(<unknown>:28773): GLib-CRITICAL **: 14:56:37.802: g_str_has_prefix: assertion 'str != NULL' failed
[E] 
(<unknown>:28773): GLib-CRITICAL **: 14:56:37.802: g_str_has_prefix: assertion 'str != NULL' failed
[E] 
(<unknown>:28773): GLib-CRITICAL **: 14:56:37.803: g_str_has_prefix: assertion 'str != NULL' failed
(<unknown>:28773): GLib-CRITICAL **: 14:56:37.803: g_str_has_prefix: assertion 'str != NULL' failed
(<unknown>:28773): GLib-CRITICAL **: 14:56:37.804: g_str_has_prefix: assertion 'str != NULL' failed
(<unknown>:28773): GLib-CRITICAL **: 14:56:37.804: g_str_has_prefix: assertion 'str != NULL' failed
(<unknown>:28773): GLib-CRITICAL **: 14:56:37.804: g_str_has_prefix: assertion 'str != NULL' failed
[E] 
(<unknown>:28773): GStreamer-CRITICAL **: 14:56:37.806: gst_event_new_caps: assertion 'gst_caps_is_fixed (caps)' failed
(<unknown>:28773): GStreamer-CRITICAL **: 14:56:37.806: gst_pad_push_event: assertion 'GST_IS_EVENT (event)' failed
[E] 
(<unknown>:28773): GStreamer-CRITICAL **: 14:56:37.819: gst_mini_object_copy: assertion 'mini_object != NULL' failed
[E] 
(<unknown>:28773): GStreamer-CRITICAL **: 14:56:37.819: gst_caps_get_structure: assertion 'GST_IS_CAPS (caps)' failed
[E] 
(<unknown>:28773): GStreamer-WARNING **: 14:56:37.846: gstpad.c:5204:store_sticky_event:<omxaudiodec0:src> Sticky event misordering, got 'segment' before 'caps'
[E] 
(<unknown>:28773): GStreamer-WARNING **: 14:56:37.863: gstpad.c:5204:store_sticky_event:<omxvideodec0:src> Sticky event misordering, got 'segment' before 'caps'
(<unknown>:28773): GStreamer-CRITICAL **: 14:56:37.864: gst_caps_get_structure: assertion 'GST_IS_CAPS (caps)' failed
[E] 
(<unknown>:28773): GStreamer-WARNING **: 14:56:37.883: gstpad.c:5204:store_sticky_event:<mmaudiosink0:sink> Sticky event misordering, got 'segment' before 'caps'
[E] 
(<unknown>:28773): GStreamer-CRITICAL **: 14:56:37.899: gst_structure_get_int: assertion 'structure != NULL' failed
[E] 
(<unknown>:28773): GStreamer-CRITICAL **: 14:56:37.899: gst_structure_get_int: assertion 'structure != NULL' failed
[E] 
(<unknown>:28773): GLib-CRITICAL **: 14:56:37.899: g_str_has_prefix: assertion 'str != NULL' failed
[E] 
(<unknown>:28773): GLib-CRITICAL **: 14:56:37.899: g_str_has_prefix: assertion 'str != NULL' failed
[E] 
(<unknown>:28773): GLib-CRITICAL **: 14:56:37.911: g_str_has_prefix: assertion 'str != NULL' failed
[E] 
(<unknown>:28773): GStreamer-WARNING **: 14:56:37.915: gstpad.c:5204:store_sticky_event:<directvideosink:sink> Sticky event misordering, got 'segment' before 'caps'
[E] 
** (<unknown>:28773): CRITICAL **: 14:56:37.917: is_repeated_pts: assertion 'sink->is_first_putimage != TRUE' failed
[E] 
(<unknown>:28773): GLib-CRITICAL **: 14:56:37.917: g_str_has_prefix: assertion 'str != NULL' failed
[E] 
(<unknown>:28773): GStreamer-CRITICAL **: 14:56:38.022: gst_clock_get_time: assertion 'GST_IS_CLOCK (clock)' failed
(<unknown>:28773): GStreamer-CRITICAL **: 14:56:38.024: gst_clock_get_time: assertion 'GST_IS_CLOCK (clock)' failed
[E] 
(<unknown>:28773): GLib-GObject-WARNING **: 14:56:38.025: g_object_get_is_valid_property: object class 'ffdemux_mov_mp4_m4a_3gp_3g2_mj2' has no property named 'is-live'
[E] 
(<unknown>:28773): GLib-GObject-WARNING **: 14:56:39.031: g_object_get_is_valid_property: object class 'ffdemux_mov_mp4_m4a_3gp_3g2_mj2' has no property named 'is-live'
[E] 
(<unknown>:28773): GLib-GObject-WARNING **: 14:56:40.031: g_object_get_is_valid_property: object class 'ffdemux_mov_mp4_m4a_3gp_3g2_mj2' has no property named 'is-live'
[E] 
(<unknown>:28773): GLib-GObject-WARNING **: 14:56:41.031: g_object_get_is_valid_property: object class 'ffdemux_mov_mp4_m4a_3gp_3g2_mj2' has no property named 'is-live'
[E] 
(<unknown>:28773): GLib-GObject-WARNING **: 14:56:42.031: g_object_get_is_valid_property: object class 'ffdemux_mov_mp4_m4a_3gp_3g2_mj2' has no property named 'is-live'
[E] 
(<unknown>:28773): GLib-GObject-WARNING **: 14:56:43.031: g_object_get_is_valid_property: object class 'ffdemux_mov_mp4_m4a_3gp_3g2_mj2' has no property named 'is-live'
[E] 
(<unknown>:28773): GLib-GObject-WARNING **: 14:56:44.031: g_object_get_is_valid_property: object class 'ffdemux_mov_mp4_m4a_3gp_3g2_mj2' has no property named 'is-live'
[E] 
(<unknown>:28773): GLib-GObject-WARNING **: 14:56:45.031: g_object_get_is_valid_property: object class 'ffdemux_mov_mp4_m4a_3gp_3g2_mj2' has no property named 'is-live'
[E] 
(<unknown>:28773): GLib-GObject-WARNING **: 14:56:46.031: g_object_get_is_valid_property: object class 'ffdemux_mov_mp4_m4a_3gp_3g2_mj2' has no property named 'is-live'
`

**Comment by xiaowei-guan** [comment]
> @xiaowei-guan If I run the avplay plugin example project on a physical Samsung TV, the app starts fine and I can play video's properly, so that's great!
> 
> The only thing I encounter in the terminal, are the below warnings and errors. Is there any way I can solve those? I ran the example project with the following command: flutter-tizen run -t lib/main.dart --release
> 
> ```
> [E] [WARN][(tid:28773)(_wl_egl_tizen_get_tizen_private)] Should create tpl_surface with this wl_egl_window first.
> [WARN][(tid:28773)(_wl_egl_tizen_get_tizen_private)] All wl_egl_window_tizen APIs will be ignored.
> [I] [EGL_DBG]: eglGetDisplay:2119, Winsys [tizen] path
> [I] [EGL_DBG]: eglInitialize:2263, [Samsung][libmali.so][rel]: Rev: v1.r23p0-01rel0.fae234be103c1a1e2f669a525ae789b2, Winsys: tizen + fbdev, nikem(0), nikel(1), pontusm(0), internal AFBC disable
> [E] 
> (process:28773): GLib-CRITICAL **: 14:56:36.005: g_path_get_basename: assertion 'file_name != NULL' failed
> [I] size of instance = 1240
> size of class = 1428
> [I] size of basesrc = 448
> size of basesrcclass = 404
> [I] gst_ffmpegtsfilter_register
> [E] 
> (<unknown>:28773): GLib-GObject-WARNING **: 14:56:36.822: g_object_set_is_valid_property: object class 'ffdemux_mov_mp4_m4a_3gp_3g2_mj2' has no property named 'input-format'
> [E] 
> (<unknown>:28773): GStreamer-WARNING **: 14:56:37.021: Trying to set string on structure field 'format', but string is not valid UTF-8. Please file a bug.
> [E] 
> (<unknown>:28773): GLib-GObject-WARNING **: 14:56:37.022: g_object_set_is_valid_property: object class 'GstMultiQueue' has no property named 'timeout-for-buffering'
> [E] 
> (<unknown>:28773): GStreamer-CRITICAL **: 14:56:37.028: gst_element_get_static_pad: assertion 'GST_IS_ELEMENT (element)' failed
> [E] 
> (<unknown>:28773): GStreamer-CRITICAL **: 14:56:37.028: gst_element_get_static_pad: assertion 'GST_IS_ELEMENT (element)' failed
> [E] 
> (<unknown>:28773): GStreamer-CRITICAL **: 14:56:37.028: gst_pad_link_full: assertion 'GST_IS_PAD (srcpad)' failed
> (<unknown>:28773): GStreamer-CRITICAL **: 14:56:37.028: gst_pad_add_probe: assertion 'GST_IS_PAD (pad)' failed
> [E] 
> (<unknown>:28773): GStreamer-CRITICAL **: 14:56:37.714: gst_structure_new_empty: assertion 'gst_structure_validate_name (name)' failed
> [I] ave_ppi_init start
> [E] 
> (<unknown>:28773): GLib-CRITICAL **: 14:56:37.798: g_str_has_prefix: assertion 'str != NULL' failed
> [E] 
> (<unknown>:28773): GLib-CRITICAL **: 14:56:37.798: g_str_has_prefix: assertion 'str != NULL' failed
> [E] 
> (<unknown>:28773): GLib-CRITICAL **: 14:56:37.798: g_str_has_prefix: assertion 'str != NULL' failed
> [E] 
> (<unknown>:28773): GLib-CRITICAL **: 14:56:37.798: g_str_has_prefix: assertion 'str != NULL' failed
> (<unknown>:28773): GLib-CRITICAL **: 14:56:37.798: g_str_has_prefix: assertion 'str != NULL' failed
> [E] 
> (<unknown>:28773): GLib-CRITICAL **: 14:56:37.799: g_str_has_prefix: assertion 'str != NULL' failed
> [E] 
> (<unknown>:28773): GLib-CRITICAL **: 14:56:37.801: g_str_has_prefix: assertion 'str != NULL' failed
> (<unknown>:28773): GLib-CRITICAL **: 14:56:37.801: g_str_has_prefix: assertion 'str != NULL' failed
> (<unknown>:28773): GLib-CRITICAL **: 14:56:37.801: g_str_has_prefix: assertion 'str != NULL' failed
> [E] 
> (<unknown>:28773): GLib-CRITICAL **: 14:56:37.802: g_str_has_prefix: assertion 'str != NULL' failed
> [E] 
> (<unknown>:28773): GLib-CRITICAL **: 14:56:37.802: g_str_has_prefix: assertion 'str != NULL' failed
> [E] 
> (<unknown>:28773): GLib-CRITICAL **: 14:56:37.803: g_str_has_prefix: assertion 'str != NULL' failed
> (<unknown>:28773): GLib-CRITICAL **: 14:56:37.803: g_str_has_prefix: assertion 'str != NULL' failed
> (<unknown>:28773): GLib-CRITICAL **: 14:56:37.804: g_str_has_prefix: assertion 'str != NULL' failed
> (<unknown>:28773): GLib-CRITICAL **: 14:56:37.804: g_str_has_prefix: assertion 'str != NULL' failed
> (<unknown>:28773): GLib-CRITICAL **: 14:56:37.804: g_str_has_prefix: assertion 'str != NULL' failed
> [E] 
> (<unknown>:28773): GStreamer-CRITICAL **: 14:56:37.806: gst_event_new_caps: assertion 'gst_caps_is_fixed (caps)' failed
> (<unknown>:28773): GStreamer-CRITICAL **: 14:56:37.806: gst_pad_push_event: assertion 'GST_IS_EVENT (event)' failed
> [E] 
> (<unknown>:28773): GStreamer-CRITICAL **: 14:56:37.819: gst_mini_object_copy: assertion 'mini_object != NULL' failed
> [E] 
> (<unknown>:28773): GStreamer-CRITICAL **: 14:56:37.819: gst_caps_get_structure: assertion 'GST_IS_CAPS (caps)' failed
> [E] 
> (<unknown>:28773): GStreamer-WARNING **: 14:56:37.846: gstpad.c:5204:store_sticky_event:<omxaudiodec0:src> Sticky event misordering, got 'segment' before 'caps'
> [E] 
> (<unknown>:28773): GStreamer-WARNING **: 14:56:37.863: gstpad.c:5204:store_sticky_event:<omxvideodec0:src> Sticky event misordering, got 'segment' before 'caps'
> (<unknown>:28773): GStreamer-CRITICAL **: 14:56:37.864: gst_caps_get_structure: assertion 'GST_IS_CAPS (caps)' failed
> [E] 
> (<unknown>:28773): GStreamer-WARNING **: 14:56:37.883: gstpad.c:5204:store_sticky_event:<mmaudiosink0:sink> Sticky event misordering, got 'segment' before 'caps'
> [E] 
> (<unknown>:28773): GStreamer-CRITICAL **: 14:56:37.899: gst_structure_get_int: assertion 'structure != NULL' failed
> [E] 
> (<unknown>:28773): GStreamer-CRITICAL **: 14:56:37.899: gst_structure_get_int: assertion 'structure != NULL' failed
> [E] 
> (<unknown>:28773): GLib-CRITICAL **: 14:56:37.899: g_str_has_prefix: assertion 'str != NULL' failed
> [E] 
> (<unknown>:28773): GLib-CRITICAL **: 14:56:37.899: g_str_has_prefix: assertion 'str != NULL' failed
> [E] 
> (<unknown>:28773): GLib-CRITICAL **: 14:56:37.911: g_str_has_prefix: assertion 'str != NULL' failed
> [E] 
> (<unknown>:28773): GStreamer-WARNING **: 14:56:37.915: gstpad.c:5204:store_sticky_event:<directvideosink:sink> Sticky event misordering, got 'segment' before 'caps'
> [E] 
> ** (<unknown>:28773): CRITICAL **: 14:56:37.917: is_repeated_pts: assertion 'sink->is_first_putimage != TRUE' failed
> [E] 
> (<unknown>:28773): GLib-CRITICAL **: 14:56:37.917: g_str_has_prefix: assertion 'str != NULL' failed
> [E] 
> (<unknown>:28773): GStreamer-CRITICAL **: 14:56:38.022: gst_clock_get_time: assertion 'GST_IS_CLOCK (clock)' failed
> (<unknown>:28773): GStreamer-CRITICAL **: 14:56:38.024: gst_clock_get_time: assertion 'GST_IS_CLOCK (clock)' failed
> [E] 
> (<unknown>:28773): GLib-GObject-WARNING **: 14:56:38.025: g_object_get_is_valid_property: object class 'ffdemux_mov_mp4_m4a_3gp_3g2_mj2' has no property named 'is-live'
> [E] 
> (<unknown>:28773): GLib-GObject-WARNING **: 14:56:39.031: g_object_get_is_valid_property: object class 'ffdemux_mov_mp4_m4a_3gp_3g2_mj2' has no property named 'is-live'
> [E] 
> (<unknown>:28773): GLib-GObject-WARNING **: 14:56:40.031: g_object_get_is_valid_property: object class 'ffdemux_mov_mp4_m4a_3gp_3g2_mj2' has no property named 'is-live'
> [E] 
> (<unknown>:28773): GLib-GObject-WARNING **: 14:56:41.031: g_object_get_is_valid_property: object class 'ffdemux_mov_mp4_m4a_3gp_3g2_mj2' has no property named 'is-live'
> [E] 
> (<unknown>:28773): GLib-GObject-WARNING **: 14:56:42.031: g_object_get_is_valid_property: object class 'ffdemux_mov_mp4_m4a_3gp_3g2_mj2' has no property named 'is-live'
> [E] 
> (<unknown>:28773): GLib-GObject-WARNING **: 14:56:43.031: g_object_get_is_valid_property: object class 'ffdemux_mov_mp4_m4a_3gp_3g2_mj2' has no property named 'is-live'
> [E] 
> (<unknown>:28773): GLib-GObject-WARNING **: 14:56:44.031: g_object_get_is_valid_property: object class 'ffdemux_mov_mp4_m4a_3gp_3g2_mj2' has no property named 'is-live'
> [E] 
> (<unknown>:28773): GLib-GObject-WARNING **: 14:56:45.031: g_object_get_is_valid_property: object class 'ffdemux_mov_mp4_m4a_3gp_3g2_mj2' has no property named 'is-live'
> [E] 
> (<unknown>:28773): GLib-GObject-WARNING **: 14:56:46.031: g_object_get_is_valid_property: object class 'ffdemux_mov_mp4_m4a_3gp_3g2_mj2' has no property named 'is-live'
> ```

@Nygashi Hello, these are gstream logs, we will remote these logs later. You can ignore it now.

**Comment by Nygashi** [comment]
Thanks! Then I will just continue and ignore the logs.
